
Carousel=function(selector)
{var me=this;me.selector=selector;me.container=$(me.selector);me.buttons={previous:new CarouselButton($("div.concarbutton.left:has(a img)",me.container.parent()),1,me),next:new CarouselButton($("div.concarbutton.right:has(a img)",me.container.parent()),-1,me)};me.ulist=$("ul",me.container);me.listItems=$("li",me.ulist);this.dispose=function()
{me.buttons=me.container=me.listItems=me.selector=me.ulist=null;};this.initialize=function()
{$(window).unload(me.dispose);if($(me.ulist).length===0)
{return;};$(me.container).parent().addClass("ccparent");$(me.buttons.previous.element).addClass("fl");me.ulist.parent().addClass("fl");$(me.buttons.previous.element).show();$(me.buttons.next.element).show();me.listItems.show();me.ulist.parent().width($(me.container).outerWidth(true)-
(($(me.buttons.previous.element).outerWidth(true)+$(me.buttons.next.element).outerWidth(true)))-18);$(me.buttons.previous.element).css("margin-right","4px");$(me.buttons.next.element).css("margin-left","5px");var listItemWidth=0;var ulistWidth=me.ulist.width();var horizontalMargin=0;var contentWidth=getMaxImgWidth();if(contentWidth===0)
{contentWidth=getMaxItemWidth();}
var numberOfitems=Math.floor(ulistWidth/contentWidth);if(numberOfitems>6)
{var extraSpace=((ulistWidth-(6*contentWidth))/6)
if(extraSpace>10)
{listItemWidth=Math.floor(contentWidth+(extraSpace-10));horizontalMargin=5;}
else
{listItemWidth=contentWidth;horizontalMargin=Math.floor(((ulistWidth/numberOfitems)-listItemWidth)/2);}
numberOfitems=6;}
else
{listItemWidth=contentWidth;horizontalMargin=Math.floor(((ulistWidth/numberOfitems)-listItemWidth)/2);}
if((jQuery.browser.msie)&&(jQuery.browser.version.substr(0,3)==="6.0")&&(horizontalMargin>0))
{horizontalMargin-=1;}
me.listItems.each(function(i,e)
{$(e).css("width",listItemWidth+"px");$(e).css("padding-left",horizontalMargin+"px");$(e).css("padding-right",horizontalMargin+"px");var img=$("img",$(e));if(img.length>0)
{if(img.parent().get(0).tagName==="A")
{img.parent().css("width",contentWidth+"px");}}});me.ulist.height(getMaxHeight());me.container.height(me.ulist.height());$(me.buttons.previous.element).css("margin-top",((me.container.height()*.5)-($(me.buttons.previous.element).outerHeight(true))*.5)+"px");$(me.buttons.next.element).css("margin-top",$(me.buttons.previous.element).css("margin-top"));};me.setVisibleItems=function(increment)
{if(increment===1)
{$(me.listItems[$(me.listItems).length-1]).prependTo($(me.ulist));}
else if(increment===-1)
{$(me.listItems[0]).appendTo($(me.ulist))};me.listItems=$("li",me.ulist);};function getMaxHeight()
{var maxHeight=0;me.listItems.each(function(i,e)
{if($(e).height()>maxHeight)
{maxHeight=$(e).height();};});me.listItems.each(function(i,e){$(e).height(maxHeight);});return maxHeight;};function getMaxItemWidth()
{var maxWidth=0;me.listItems.each(function(i,e)
{if($(e).width()>maxWidth)
{maxWidth=$(e).width();};});return maxWidth;};function getMaxImgWidth()
{var maxWidth=0;me.listItems.each(function(i,e)
{var img=$("img",$(e));if(img.length>0)
{if(img.width()>maxWidth)
{maxWidth=img.width();};}});return maxWidth;};me.initialize();};CarouselButton=function(element,increment,parent)
{var me=this;me.element=element;me.increment=increment;me.parent=parent;me.imageOn=$("a img.on",me.element);me.imageOff=$("a img.off",me.element);this.dispose=function()
{me.parent=me.increment=me.element=null;};this.initialize=function()
{$(window).unload(me.dispose);$(me.element).click(clickHandler);};clickHandler=function(ev)
{me.parent.setVisibleItems(me.increment);};mouseOverHandler=function(ev)
{$(me.imageOff).hide();$(me.imageOn).show();};mouseOutHandler=function(ev)
{$(me.imageOn).hide();$(me.imageOff).show();};me.initialize();};
$(function(){$(".tabbedcontent").each(function(i){var tc=$(this),tc_index=i,tc_tabindex=0,tc_ul=$("<ul/>"),tc_cookie=document.cookie.split("; "),tc_headcount=0,tc_headwidth=-10;$(".mycontent",tc).before(tc_ul.addClass("tab"));for(var j=0;j<tc_cookie.length;j++){var arr=tc_cookie[j].split("=");if(location.href+"tc_tabindex"+tc_index==arr[0]){tc_tabindex=arr[1];break;}};tc.parent("div.content").css("padding-left","0");tc.parent("div.content").css("padding-right","0");if($.browser.msie){$(".mycontent",tc).hide();$(".mycontent",tc).width(tc.parent("div.content").width()-2).show();}
if(tc.parent().prev("div").children("span.text").html()){var tc_h2=tc.parent().prev("div").children("span.text");tc_h2.appendTo(tc_ul).replaceWith("<li>"+tc_h2.html()+"</li>");tc_headwidth=tc_ul.children("li:first").width();tc_headcount=1;}
var _totalwidth=tc.parent("div.content").width()-2;var _lncount=$(".mycontent div h3",tc).length;var _tabswidth=_totalwidth-(_lncount-1)*5-(tc_headwidth+28);var _mod=_tabswidth%_lncount||0;var _tabwidth=_lncount==0?_totalwidth-19:(_tabswidth-_mod)/_lncount;var showtap=function(i){$(".mycontent div.lngroup",tc).each(function(){$(this).css("display","none")});$("div.mycontent div.lngroup:eq("+i+")",tc).css("display","block");$("li:eq("+(parseInt(i)+tc_headcount)+")",tc_ul).addClass("sel");}
tc_ul.width(_totalwidth);$(".mycontent div h3",tc).each(function(){$(this).appendTo(tc_ul).replaceWith("<li><a href=\"javascript:;\" title='"+$(this).html()+"'>"+$(this).html()+"</a></li>");});$("li",tc_ul).each(function(){$(this).css("width",_tabwidth);});if(tc_headcount>0){$("li:first",tc_ul).addClass("first").css("width",tc_headwidth);}
else{$("li:first",tc_ul).addClass("nohead");}
$("li:last",tc_ul).addClass("last").css("width",_tabwidth+_mod);showtap(tc_tabindex);tc.siblings().css("overflow","hidden");$("li",tc_ul).each(function(k){if(tc_headcount>0){k=k-1;if(k==-1)return;}
$(this).bind("click",function(){$("li",tc_ul).removeClass("sel");showtap(k);document.cookie=location.href+"tc_tabindex"+tc_index+"="+k;});});});});$(function(){$(".mostpopular").each(function(i){var mp=$(this),mp_index=i,mp_tabindex=0,mp_ul=$("<ul/>"),mp_content=$(".mycontent",mp),li_count=$(".mycontent > div",mp).length;mp_content.before(mp_ul.addClass("tab"));$(".imglinkabslist5,.cf",mp).parent().addClass("editorschoice");mp.parent("div.content").css("padding-left","0");mp.parent("div.content").css("padding-right","0");if(li_count>1){var mp_cookie=document.cookie.split("; ");for(var j=0;j<mp_cookie.length;j++){var arr=mp_cookie[j].split("=");if(location.href+"mp"+mp_index==arr[0]){mp_tabindex=arr[1];break;}};if($.browser.msie){mp_content.hide();}
var mp_width=mp.parent().width()-2;mp_content.width(mp_width).show();var showtab=function(k){$(".mycontent > div",mp).each(function(){$(this).css("display","none")});$("div.mycontent > div:eq("+k+")",mp).css("display","block");$("li:eq("+k+")",mp_ul).addClass("sel");}
$(".mycontent div h3",mp).each(function(){$(this).appendTo(mp_ul).replaceWith("<li><a href=\"javascript:;\" title='"+$(this).html()+"'>"+$(this).html()+"</a></li>");});$("li",mp_ul).each(function(m){$(this).click(function(){$("li",mp_ul).removeClass("sel");showtab(m);document.cookie=location.href+"mp"+mp_index+"="+m;});});$("li:first",mp_ul).addClass("first");$("li:last",mp_ul).addClass("last");showtab(mp_tabindex);mp.siblings().css("overflow","hidden");}
else{mp_ul.remove();mp.removeClass();mp_content.removeClass("mycontent");}
$(".mptab",mp_content).css("padding","0px 10px 10px 9px");$(".editorschoice",mp_content).css("padding-bottom","1px");$(".mptab .linklist16 .last.bottom",mp_content).css("padding-bottom","0px");$("ul.moregaps",mp_content).css("margin-top","9px").children("li").css("padding-left","6px");if(mp_content.hasClass("tabnum")){$(".mptab",mp_content).each(function(){$(".imglinkabslist5 > li,.cf > li",$(this)).each(function(i){$(this).children("a:eq(1)").before("<p style='padding-right:8px; display:inline; font-weight:bold; font-family:Tahoma; font-size:0.98em; color:#666;'>"+(i+1)+".</p>");});});}});});
function GetAttributeList(source){var className=null;if($(source).hasClass("verticalslider")){className=$(source).attr("class");}
else{className=$(source).parent(".verticalslider > .slideritem").parent().attr("class");}
var classArray=className.toString().split("_");return classArray;}
function LoadVerticalSlider(){var verticalSlider=$(".verticalslider");for(i=0;i<verticalSlider.length;i++){var verticalSliderClass=$(verticalSlider[i]).attr("class");var classArray=GetAttributeList(verticalSlider[i]);var speed=classArray[1];var defaultPanel=parseInt(classArray[2]);var panes=$(verticalSlider[i]).children(".slideritem");var arrowImageAltText=GetArrowImageAltText(verticalSlider[i]);var currentPane=null;for(j=0;j<panes.length;j++){currentPane=$(verticalSlider[i]).children(".slideritem:eq("+j+")");if(j===defaultPanel){InsertArrowImage(currentPane,"open",arrowImageAltText);currentPane.toggleClass("selected");}
else{InsertArrowImage(currentPane,"close",arrowImageAltText);TogglePane(currentPane,true,"fast");}
if(j==0){currentPane.addClass("first");}}
$(verticalSlider[i]).addClass("verticalsliderjs");}
$(".slideritem > .heading").click(function()
{VerticalSliderToggleHandler($(this));});$(".slideritem span a").click(function(event)
{if(!$(this).hasClass("vs_sliderarrowlink")){event.stopPropagation();}});function VerticalSliderToggleHandler(me){var pane=me.parent(".slideritem");var paneToCollapse=null;if(!pane.hasClass("selected")){paneToCollapse=pane.siblings(".slideritem.selected");}
else{paneToCollapse=pane;}
var attributeList=GetAttributeList(me);if(!pane.hasClass("selected")){SwapArrowImage(paneToCollapse,"close");TogglePane(paneToCollapse,false,attributeList[1]);SwapArrowImage(pane,"open");TogglePane(pane,false,attributeList[1]);}
else{SwapArrowImage(paneToCollapse,"close");TogglePane(paneToCollapse,false,attributeList[1]);}}
function TogglePane(pane,forceClose,animationSpeed){if(pane===null||pane===undefined){return;}
var innerPane=$(pane).children().not(".heading");innerPane.slideToggle(speed);if(forceClose==false){pane.toggleClass("selected");}}}
function SwapArrowImage(pane,action){var arrowImage=$(pane).find(".vs_sliderarrow");var arrowImagePath=GetArrowImage(action);if(arrowImagePath!=undefined&&arrowImagePath!=null){arrowImage.attr("src",arrowImagePath);}}
function GetArrowImage(action){if(action==="open"){return $(".vs_openedImgPathHidden:first").text();}else if(action==="close"){return $(".vs_closedImgPathHidden:first").text();}else{return;}}
function GetArrowImageAltText(container){if(container==null){return;}
return $(container).find(".vs_imageAltText:first").text();}
function InsertArrowImage(pane,action,arrowImageAltText){if(arrowImageAltText==null){return;}
var arrowImagePath=GetArrowImage(action);var arrowLink=$(document.createElement("a"));arrowLink.attr("title",arrowImageAltText);var arrowImage=$(document.createElement("img"));arrowImage.attr("src",arrowImagePath);arrowImage.attr("alt",arrowImageAltText);arrowLink.append(arrowImage);if($(pane).find(".heading .text").length>0){$(pane).find(".heading .text").after(arrowLink);}
else{$(pane).find(".heading").prepend(arrowLink);}
arrowImage.attr("class","vs_sliderarrow");arrowLink.attr("class","vs_sliderarrowlink");}
$(document).ready(function(){LoadVerticalSlider();});
WeatherSearch=function(selector,args){var me=this;me.selector=selector;me.container=$(me.selector);me.formContainer=me.wtrContainer=me.searchContainer=null;me.formContainer=$("form",me.container);me.errorpanel=me.searchpanel=null;me.searchresponse=null;me.forecastBindings=new ForecastBindings();me.childc2=me.childc1=null;me.locfield=null;me.feedCount=0;me.defaultcity=args[0];me.tempformat=args[1];me.culture=args[2];me.cols=args[3];me.maxfeeds=args[4];me.loadmessage=args[5];me.closetext=args[6];me.duperr=args[7];me.maxfeedserr=args[8];me.invaliderr=args[9];me.emptyerr=args[10];me.servicename=args[11];me.imagepath=args[12];me.daystoforecast=args[13];me.locCodeRegEx=new RegExp("[a-zA-Z]{2,}:[a-zA-Z0-9]+","i");function showMessage(color,message){if(message!="&nbsp;"){$(me.errorpanel).css("color",color);$(me.errorpanel).html(message);$(me.errorpanel).show();}else{$(me.errorpanel).hide();}};function getCookie(name){var cookieName=name+"=";var cooks=document.cookie.split(';');if(cooks.length>0){for(var i=0;i<cooks.length;i++){var ca=cooks[i];while(ca.charAt(0)==' '){ca=ca.substring(1,ca.length);}
if(ca.indexOf(cookieName)==0){return ca.substring(cookieName.length,ca.length);}}}
return null;};function setCookie(cookieName,cookieValue,expireDate){var newExpire;if(expireDate!=null||expireDate!=""){newExpire=new Date();newExpire.setYear(newExpire.getFullYear()+5);}
else{newExpire=expireDate;};if(typeof document!="undefined"){document.cookie="WeatherSearch=;expires="+new Date().toGMTString();document.cookie=cookieName+"="+cookieValue+";expires="+newExpire.toGMTString()+";path=/";return true;};return false;};function getPersistState(){return getCookie("WeatherSearch");};function setPersistState(){var cookieValue="";if(me.forecastBindings.size()!=0){for(var loc in me.forecastBindings.locations){cookieValue+=loc+"|";}
cookieValue=cookieValue.substring(0,cookieValue.length-1);}
setCookie("WeatherSearch",cookieValue);};function cancelEvent(evt){evt.cancelBubble=true;};function closeSearch(){$(me.errorpanel).html("&nbsp");$(me.errorpanel).hide();$(me.searchpanel).empty();$(me.childc2).hide();me.locfield.val("");return false;};function hasBindings(loc){if(me.forecastBindings.locations[loc]){return true;}else{me.forecastBindings.locations[loc]=loc;return false;}};function getWeatherForecast(location,node){if(me.maxfeeds!=0){if(me.forecastBindings.size()==me.maxfeeds){showMessage("red",me.maxfeedserr.replace("{#do not remove this text#}",me.maxfeeds));return;}}
if(hasBindings(location)){showMessage("red",me.duperr);return;}
if(me.wtrContainer==null){me.wtrContainer=$("<div class='wtrcon'/>");me.wtrContainer.insertBefore(me.childc1);$(me.childc1).prepend("<div class='separator'/>");}
var weatherInfo=$(node);var locationName=weatherInfo.attr("weatherlocationname");var locationCode=weatherInfo.attr("weatherlocationcode");var linkurl=weatherInfo.attr("url");var imagerelativeurl=weatherInfo.attr("imagerelativeurl");var degreetype=weatherInfo.attr("degreetype");var curweather=$("current",weatherInfo);var curtmp=curweather.attr("temperature");var cursky=curweather.attr("skytext");var wtr=$("<div class='wtr'/>");wtr.appendTo(me.wtrContainer);var hdrText=locationName;var contentarea=$(me.container).parent().parent().parent();if(contentarea.length>0&&$(contentarea).hasClass("mpreg2")){hdrText+="<br/>";}
else{hdrText+="&nbsp;&nbsp;&nbsp;&nbsp;";}
hdrText+=curtmp+"\xB0"+degreetype.toLowerCase()+"&nbsp;&nbsp;&nbsp;&nbsp;"+cursky;var wtrhdr=$("<div class='wtrhdr'></div>");var wtrhdrlink=$("<a href='"+linkurl+"'>"+hdrText+"</a>");wtrhdrlink.appendTo(wtrhdr);var mticons=$("<span class='mticons'/>");var btnToggle=$("<img src ='"+me.imagepath+"categoryclosed.gif' align='absMiddle'>");btnToggle.toggle(function(evt){$(this).attr("src",me.imagepath+"categoryOpen.gif");$(wtrlist).hide();},function(evt){$(this).attr("src",me.imagepath+"categoryClosed.gif");$(wtrlist).show();});var btnKill=$("<img src ='"+me.imagepath+"categoryKill.gif' align='absMiddle'>");btnKill.click(function(evt){$(wtr).remove();delete me.forecastBindings.locations[locationCode];if(me.forecastBindings.size()==0){$("div.separator").remove();}
return false;});mticons.append(btnToggle);mticons.append(btnKill);wtrhdr.append(wtrhdrlink).append(mticons);wtrhdr.appendTo(wtr);var wtrlist=$("<ul class='wtrlist'/>");wtrlist.appendTo(wtr);var forenums=$(node).find("forecast").length;if(me.daystoforecast!=-1&&me.daystoforecast<forenums){forenums=me.daystoforecast;}
$("forecast",node).each(function(i){var wtrli=null;if(i<forenums){if(i==0){wtrli=$("<li class='first'/>");}
else if(i==forenums-1){wtrli=$("<li class='last'/>");}
else{wtrli=$("<li></li>");}
var wtrdays=$("<div class='wtrdays'/>");var wtrday=$("<div class='wtrday'>"+$(this).attr("day")+"</div>");var wtrimg=$("<img height='21' width='35' src="+imagerelativeurl+$(this).attr("skycodeday")+".gif alt = '"+$(this).attr("skytextday")+"' title = '"+$(this).attr("skytextday")+"'></img>");var wtrtmp=$("<div class='wtrtmp'>"+$(this).attr("high")+"/"+$(this).attr("low")+"</div>");$(wtrli).append(wtrdays.append(wtrday).append(wtrimg).append(wtrtmp));wtrlist.append(wtrli);}});closeSearch();};function resultClick(evt){var evtEl=null;if($.browser.mozilla){evtEl=evt.target;}
else{evtEl=evt.srcElement;}
if(evt.type.toLowerCase()=="click"){var loc=$(evtEl).attr("nc:value");var pos=$(evtEl).attr("nc:position");var node=$(me.searchresponse).find("weather").get(pos);getWeatherForecast(loc,node);}
return false;};function searchResults(data,textstatus){var weatherdata=$(data);if(weatherdata==null||weatherdata.find("weather").length==0){showMessage("red",me.invaliderr);}else{$(me.errorpanel).hide();$(me.searchpanel).empty();if(weatherdata.find("weather").length>1){me.searchresponse=weatherdata;var searchResult=null;$("weather",data).each(function(i){searchResult=$("<div class='wtrres'/>").appendTo(me.searchpanel);linkResult=$("<a href='#'></a>");linkResult.text($(this).attr("weatherlocationname"));linkResult.attr("nc:value",$(this).attr("weatherlocationcode"));linkResult.attr("nc:position",i);linkResult.appendTo(searchResult);linkResult.bind("click",null,resultClick);});searchResult=$("<div class='wtrres close'/>").appendTo(me.searchpanel);linkClose=$("<a href='#'></a>");linkClose.text(me.closetext);linkClose.appendTo(searchResult);linkClose.click(function(){closeSearch();});$(me.childc2).show();}
else{var node=weatherdata.find("weather").get(0);var loc=$(node).attr("weatherlocationcode");if(loc==null){showMessage("red",me.emptyerr);}
else{getWeatherForecast(loc,node);}}}};function getForecast(loc,search){showMessage("#999",me.loadmessage);if(search){$.get(me.servicename,{"weasearchstr":loc,"weadegreetype":me.tempformat.toUpperCase(),"culture":me.culture,"rand":Math.random()},searchResults,"xml");}else{$.get(me.servicename,{"wealocations":loc.replace("|","\\r"),"weadegreetype":me.tempformat.toUpperCase(),"culture":me.culture,"rand":Math.random()},searchResults,"xml");}
return false;};function formSubmit(evt){var locValue=me.locfield.val();$(me.locfield).val("");if(locValue!=""&&locValue!=me.locfield.attr("initvalue")){if(me.locCodeRegEx.test(locValue)){return getForecast(locValue,false);}
else{return getForecast(locValue,true);}}
return false;};function addPersistedForecasts(){var states=getPersistState();if(states!=null){var bindings=states.split("|");for(var i=0;i<bindings.length;i++){getForecast(bindings[i],false);}}else{getForecast(me.defaultcity,false);}};this.dispose=function(){setPersistState();me.selector=me.container=me.formContainer=me.errorpanel=null;me.forecastBindings=null;me.searchresponse=null;};this.initialize=function(){$(window).unload(this.dispose);me.childc1=$("div.child.c1",me.container);me.childc2=$("div.child.c2",me.container);me.errorpanel=$("<div class='wtrerr'>&nbsp;</div>");me.errorpanel.insertBefore(me.childc2);me.errorpanel.hide();me.formContainer.removeAttr("action");me.formContainer.remove("method");$("p",me.formContainer).hide();$("div > label",me.formContainer).hide();me.locfield=$("input:text",me.formContainer);me.locfield.attr("name",me.locfield.id);me.locfield.attr("autocomplete","on");me.locfield.attr("initvalue",me.locfield.val());me.locfield.focus(function(){closeSearch();});me.searchContainer=$("div.child.c2 > div.richtext",me.container);if(me.searchContainer.length==0){me.childc2.append("<div class='richtext'/>");me.searchContainer=$("div.child.c2 > div.richtext",me.container);}
me.searchpanel=$("<div class='wtrscrh'/>");me.searchpanel.insertAfter(me.searchContainer);me.childc2.hide();me.formContainer.bind("submit",null,formSubmit);addPersistedForecasts();};me.initialize();};ForecastBindings=function(){me=this;me.locations={};this.initialize=function(){};this.size=function(){var locs=new Array();var i=0;for(loc in me.locations){locs[i]=loc;i++;}
return locs.length;};me.initialize();};var VideoExperience={};VideoExperience.Trim=function(a){return a.replace(/(^\s*)|(\s*$)/g,"")};VideoExperience.GenerateKeyword=function(f){var d=/(?!But|The|However|By)(([A-Z\u00C5\u00C4\u00D6][\w\u00C5\u00E5\u00C4\u00E4\u00D6\u00F6]*('[\w\u00C5\u00E5\u00C4\u00E4\u00D6\u00F6]\b)?)(\s*))+(([A-Z\u00C5\u00C4\u00D6][\w\u00C5\u00E5\u00C4\u00E4\u00D6\u00F6]*)|((\d+\.)+\d+))/g,c={},b=f;b=" "+b;var a=d.exec(b);while(a!=null&&a[0]!=null){a[0]=VideoExperience.Trim(a[0]);c[a[0]]=a[0];a=d.exec(b)}var e=[];for(key in c)e.push(c[key]);return e};VideoExperience.RelatedVideoPlayer=function(b){var d=this,c="&mk=",a=d;a.currentIndex=0;a.width=b.width;a.height=b.height;a.playerVars=b.playerVars;a.keywords=b.keywords;a.mk=b.mk;a.type=b.type;a.playerId=b.playerId;a.widgetType=b.widgetType;d.dispose=function(){a.currentIndex=a.width=a.height=a.keywords=null;a.playerVars=a.mk=a.type=a.widgetType=null};d.initialize=function(){$(window).unload(a.dispose)};d.render=function(){e(a.keywords[a.currentIndex])};function f(){var b="search.aspx?q=";if(a.type==="flash"){a.playerVars["player.c"]="vcq";a.playerVars["player.vcq"]=b+a.keywords[a.currentIndex]+c+a.mk;Msn.Video.createWidget("div_"+a.playerId,a.widgetType,a.width,a.height,a.playerVars,a.playerId)}if(a.type==="silverlight"){var c=new Msn.VideoSL.Inline("div_"+a.playerId);a.playerVars["c"]="vcq";a.playerVars["vcq"]=b+a.keywords[a.currentIndex]+c+a.mk;c.Build(a.playerVars,a.width,a.height)}}function e(b){if(b)$.ajax({type:"GET",url:"http://edge1.catalog.video.msn.com/search.aspx?q="+b+c+a.mk+"&ps=1&responseEncoding=json&callbackName=?",dataType:"jsonp",jsonp:"callbackName",success:function(b){if(b&&b.$total&&parseInt(b.$total)!==0)f();else{a.currentIndex++;e(a.keywords[a.currentIndex])}}})}};VideoExperience.GetFilmsAndActorsNames=function(l,k,i){var j="']:first",b="name",e=l||"movietitle_film",d=k||"movietitle_actor",c=$("input[name]:hidden").filter(function(){return $(this).attr(b)===e||$(this).attr(b)===d}),a=[];if(c.size()>0){var f=c.filter(":first");a[a.length]=encodeURIComponent(f.val());var h=c.filter("[name='"+e+j),g=c.filter("[name='"+d+j);if(f.attr(b)===e&&g.size()>0)a[a.length]=encodeURIComponent(g.val());if(f.attr(b)===d&&h.size()>0)a[a.length]=encodeURIComponent(h.val())}if(i)a[a.length]=encodeURIComponent(i);return a};VideoExperience.ParseKeywordsFromHtml=function(e){try{var b=document.getElementById(e).innerHTML}catch(f){}if(!b)return "";var d=/<\/?[^>]+>/g,c=b.replace(d,"").replace(/\n/g," ");if(c.length<=0)return "";var a=[];a=VideoExperience.GenerateKeyword(c);if(a.length>0)return a[0];return ""};VideoExperience.ParseKeywordsFromSEOKeywords=function(b){var c=/\w+(\s+\w*)*/g,a=b.match(c);if(a!=null&&a.length>0)return a[0];return ""};