<?php
echo"<table width=\"998\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"themes/XD-Obstuse/images/FT/XD-Obstuso_FT_03.gif\">\n";
  echo "  <tbody>\n";
  echo "    <tr>\n";
  echo "      <td><table width=\"100%\" height=\"25\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n";
  echo "        <tbody>\n";
  echo "          <tr>\n";
  echo "            <td width=\"238\" align=\"center\"><IMG SRC=\"themes/XD-Obstuse/images/FT/XD-Obstuso_FT_01.gif\" WIDTH=238 HEIGHT=73 ALT=\"\"></td>\n";
  echo "            <td valign=\"bottom\"><div align=\"center\">\n";
  echo "              <table width=\"49%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n";
  echo "                <tbody>\n";
  echo "                  <tr>\n";
  echo "                    <td align=\"center\" valign=\"bottom\"><div align=\"left\">\n";
  echo "                      <table id=\"Table_01\" height=\"73\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n";
  echo "                        <tr>\n";
  echo "                          <td width=\"312\">\n";
  echo "                            <SCRIPT src=\"for3.js\"></SCRIPT><SCRIPT language=javascript>carregaFlash('themes/XD-Obstuse/Flash/Fnav.swf','312','73');</SCRIPT></td>\n";
  echo "                        </tr>\n";
  echo "                      </table>\n";
  echo "                    </div></td>\n";
  echo "                  </tr>\n";
  echo "                </tbody>\n";
  echo "              </table>\n";
  echo "              </div>              </td>\n";
  echo "            <td width=\"80\"><IMG SRC=\"themes/XD-Obstuse/images/FT/XD-Obstuso_FT_07.gif\" WIDTH=80 HEIGHT=73 ALT=\"\"></td>\n";
  echo "          </tr>\n";
  echo "        </tbody>\n";
  echo "      </table>\n";
  echo "        <table width=\"100%\" height=\"25\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n";
  echo "          <tbody>\n";
  echo "            <tr>\n";
  echo "              <td width=\"238\" align=\"center\"><TABLE WIDTH=238 BORDER=0 CELLPADDING=0 CELLSPACING=0>\n";
  echo "                <TR>\n";
  echo "                  <TD COLSPAN=3> <IMG SRC=\"themes/XD-Obstuse/images/FT/XD-Obstuso_FT_DL_01.gif\" WIDTH=238 HEIGHT=23 ALT=\"\"></TD>\n";
  echo "                </TR>\n";
  echo "                <TR>\n";
  echo "                  <TD ROWSPAN=2> <IMG SRC=\"themes/XD-Obstuse/images/FT/XD-Obstuso_FT_DL_02.gif\" WIDTH=23 HEIGHT=156 ALT=\"\"></TD>\n";
  echo "                  <TD height=\"116\" background=\"themes/XD-Obstuse/images/FT/XD-Obstuso_FT_DL_03.gif\" align=\"center\">BANNER FIXO<br><a href=\"modules.php?name=Content&pa=showpage&pid=1\">Clique aqui para contato.</a></TD>\n";
  echo "                  <TD ROWSPAN=2> <IMG SRC=\"themes/XD-Obstuse/images/FT/XD-Obstuso_FT_DL_04.gif\" WIDTH=49 HEIGHT=156 ALT=\"\"></TD>\n";
  echo "                </TR>\n";
  echo "                <TR>\n";
  echo "                  <TD> <IMG SRC=\"themes/XD-Obstuse/images/FT/XD-Obstuso_FT_DL_05.gif\" WIDTH=166 HEIGHT=40 ALT=\"\"></TD>\n";
  echo "                </TR>\n";
  echo "              </TABLE></td>\n";
  echo "              <td width=\"100%\"><div align=\"center\">\n";
  echo "                <table width=\"87%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"Table_01\">\n";
  echo "                  <tr>\n";
  echo "                    <td>\n";
  echo "                      <div align=\"center\">\n";
  echo " $tbanners2 \n";
  echo "</div></td>\n";
  echo "                  </tr>\n";
  echo "                </table>\n";
  echo "              </div></td>\n";
  echo "              <td width=\"238\"><TABLE WIDTH=238 BORDER=0 CELLPADDING=0 CELLSPACING=0>\n";
  echo "                <TR>\n";
  echo "                  <TD ROWSPAN=5> <IMG SRC=\"themes/XD-Obstuse/images/FT/XD-Obstuso_FT_CR_01.gif\" WIDTH=46 HEIGHT=179 ALT=\"\"></TD>\n";
  echo "                  <TD> <IMG SRC=\"themes/XD-Obstuse/images/FT/bah01.gif\" WIDTH=167 HEIGHT=50 ALT=\"\"></TD>\n";
  echo "                  <TD ROWSPAN=5> <IMG SRC=\"themes/XD-Obstuse/images/FT/XD-Obstuso_FT_CR_03.gif\" WIDTH=25 HEIGHT=179 ALT=\"\"></TD>\n";
  echo "                </TR>\n";
  echo "                <TR>\n";
  echo "                  <TD align=\"center\">BANNER FIXO<br><a href=\"modules.php?name=Content&pa=showpage&pid=1\">Clique aqui para contato.</a><br><br><br><br><br><br></TD>\n";
  echo "                </TR>\n";
  echo "                 </TABLE></td>\n";
  echo "            </tr>\n";
  echo "          </tbody>\n";
  echo "        </table></td>\n";
  echo "    </tr>\n";
  echo "  </tbody>\n";
echo "</TABLE>\n";
?>