<?php
echo "<HTML>\n";
echo "<HEAD>\n";
echo "<TITLE>XD-Obtuse</TITLE>\n";
echo "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n";
echo "</HEAD>\n";
echo "<BODY leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\n";
echo "\n";
echo"<TABLE width=\"998\" align=\"center\" BORDER=0 CELLPADDING=0 CELLSPACING=0 background=\"themes/XD-Obstuse/images/HD/XD-Obstuso_HD_03.gif\">\n";
  echo "  <TR>\n";
  echo "    <TD ><TABLE width=\"100%\" BORDER=0 CELLPADDING=0 CELLSPACING=0>\n";
  echo "        <TR>\n";
  echo "          <TD ><TABLE width=\"337\" BORDER=0 CELLPADDING=0 CELLSPACING=0>\n";
  echo "              <TR>\n";
  echo "                <TD align=\"center\"><SCRIPT src=\"banner1.js\"></SCRIPT><SCRIPT language=javascript>carregaFlash('banner1.swf','499','187');</SCRIPT></TD>\n";
  echo "              </TR>\n";
  echo "          </TABLE></TD>\n";
  echo "          <TD height=\"187\"><SCRIPT src=\"banner2.js\"></SCRIPT><SCRIPT language=javascript>carregaFlash('banner18.swf','499','187');</SCRIPT></TD>\n";
  echo "        </TR>\n";
  echo "      </TABLE>\n";
  echo "        <TABLE width=\"100%\" BORDER=0 CELLPADDING=0 CELLSPACING=0>\n";
  echo "          <TR>\n";
  echo "            <TD ><TABLE width=\"275\" BORDER=0 CELLPADDING=0 CELLSPACING=0>\n";
  echo "                <TR>\n";
  echo "                  <TD ><SCRIPT src=\"for1875.js\"></SCRIPT><SCRIPT language=javascript>carregaFlash('xdmenu.swf','275','70');</SCRIPT></TD>\n";
  echo "                </TR>\n";
  echo "            </TABLE></TD>\n";
  echo "            <TD width=\"100%\" ><TABLE width=\"275\" BORDER=0 align=\"center\" CELLPADDING=0 CELLSPACING=0>\n";
  echo "                <TR>\n";
  echo "                  <TD ><SCRIPT src=\"for45.js\"></SCRIPT><SCRIPT language=javascript>carregaFlash('themes/XD-Obstuse/Flash/login.swf','251','70');</SCRIPT></TD>\n";
  echo "                  <TD ></TD>\n";
  echo "                </TR>\n";
  echo "            </TABLE></TD>\n";
  echo "            <TD ><IMG SRC=\"themes/XD-Obstuse/images/HD/XD-Obstuso_HD_11.gif\" WIDTH=46 HEIGHT=70 ALT=\"\"></TD>\n";
  echo "          </TR>\n";
  echo "      </TABLE></TD>\n";
  echo "  </TR>\n";
echo "</TABLE>\n";
?>