<?php
echo "<HTML>\n";
echo "<HEAD>\n";
echo "<TITLE>XD-Obtuse</TITLE>\n";
echo "<META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n";
echo "<!-- Copyright © 2003 Xtrato Dot Com. All rights reserved. -->\n";
echo "</HEAD>\n";
echo "<BODY  leftmargin=\"0\" topmargin=\"0\" marginwidth=\"0\" marginheight=\"0\">\n";
echo "\n";
echo"<TABLE width=\"998\" align=\"center\" BORDER=0 CELLPADDING=0 CELLSPACING=0 background=\"themes/XD-Obstuse/images/HD/XD-Obstuso_HD_03.gif\">\n";
  echo "  <TR>\n";
  echo "    <TD ><TABLE width=\"100%\" BORDER=0 CELLPADDING=0 CELLSPACING=0>\n";
  echo "        <TR>\n";
  echo "          <TD ><TABLE width=\"337\" BORDER=0 CELLPADDING=0 CELLSPACING=0>\n";
  echo "              <TR>\n";
  echo "                <TD ><object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0\" width=\"337\" height=\"187\">\n";
  echo "                  <param name=\"movie\" value=\"themes/XD-Obstuse/Flash/XDlogo.swf\">\n";
  echo "                  <param name=\"quality\" value=\"high\">\n";
  echo "                  <embed src=\"themes/XD-Obstuse/Flash/XDlogo.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\" width=\"337\" height=\"187\"></embed>\n";
  echo "                </object></TD>\n";
  echo "              </TR>\n";
  echo "          </TABLE></TD>\n";
  echo "          <TD width=\"100%\" >&nbsp;</TD>\n";
  echo "          <TD ><img src=\"themes/XD-Obstuse/images/HD/XD-Obstuso_HD_05.gif\" width=201 height=187 alt=\"\"></TD>\n";
  echo "        </TR>\n";
  echo "      </TABLE>\n";
  echo "        <TABLE width=\"100%\" BORDER=0 CELLPADDING=0 CELLSPACING=0>\n";
  echo "          <TR>\n";
  echo "            <TD ><TABLE width=\"275\" BORDER=0 CELLPADDING=0 CELLSPACING=0>\n";
  echo "                <TR>\n";
  echo "                  <TD >                    <object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0\" width=\"275\" height=\"70\">\n";
  echo "                      <param name=\"movie\" value=\"themes/XD-Obstuse/Flash/XDMenu.swf\">\n";
  echo "                      <param name=\"quality\" value=\"high\">\n";
  echo "                      <embed src=\"themes/XD-Obstuse/Flash/XDMenu.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\" width=\"275\" height=\"70\"></embed>\n";
  echo "                  </object></TD>\n";
  echo "                </TR>\n";
  echo "            </TABLE></TD>\n";
  echo "            <TD width=\"100%\" ><TABLE width=\"275\" BORDER=0 align=\"center\" CELLPADDING=0 CELLSPACING=0>\n";
  echo "                <TR>\n";
  echo "                  <TD >$theuser</TD>\n";
  echo "                  <TD ></TD>\n";
  echo "                </TR>\n";
  echo "            </TABLE></TD>\n";
  echo "            <TD ><IMG SRC=\"themes/XD-Obstuse/images/HD/XD-Obstuso_HD_11.gif\" WIDTH=46 HEIGHT=70 ALT=\"\"></TD>\n";
  echo "          </TR>\n";
  echo "      </TABLE></TD>\n";
  echo "  </TR>\n";
echo "</TABLE>\n";
?><?
echo"<table width=100% border=0 cellpadding=0 cellspacing=0>\n";
  echo " <tr>\n";
  echo "   <td width=\"216\" height=\"100%\">\n";
  echo "     <table width=216 height=\"100%\" border=0 cellpadding=0 cellspacing=0>\n";
  echo "       <tr>\n";
  echo "         <td background=\"themes/XD-Obstuse/images/leftBG.gif\"> <img src=\"themes/XD-Obstuse/images/leftBG.gif\" width=20 height=100% alt=\"\"></td>\n";
  echo "         <td width=\"100%\" height=\"100%\" background=\"themes/XD-Obstuse/images/mainBG.gif\"><img src=\"themes/XD-Obstuse/images/HD/spacer.gif\" width=179 height=100% alt=\"\"></td>\n";
  echo "         <td background=\"themes/XD-Obstuse/images/rightBG.gif\"> <img src=\"themes/XD-Obstuse/images/rightBG.gif\" alt=\"\" width=17 height=100%></td>\n";
  echo "       </tr>\n";
  echo "     </table></td>\n";
  echo "   <td width=\"100%\" background=\"themes/XD-Obstuse/images/mainBG.gif\"><table width=98% height=\"26\" border=0 align=\"center\" cellpadding=0 cellspacing=0>\n";
  echo "       <tr>\n";
  echo "         <td valign=\"top\"><table width=100% border=0 align=\"center\" cellpadding=0 cellspacing=0>\n";
  echo "             <tr>\n";
  echo "               <td width=\"20\" valign=\"top\"><img src=\"themes/XD-Obstuse/images/TBL/XD-Obstuso_TBL_01.gif\" width=57 height=37 alt=\"\"></td>\n";
  echo "               <td width=\"100%\" background=\"themes/XD-Obstuse/images/TBL/XD-Obstuso_TBL_03.gif\"><div align=\"center\"></div></td>\n";
  echo "               <td width=\"19\" valign=\"top\"><div align=\"right\"> <img src=\"themes/XD-Obstuse/images/TBL/XD-Obstuso_TBL_05.gif\" width=58 height=37 alt=\"\"></div></td>\n";
  echo "             </tr>\n";
  echo "           </table>\n";
  echo "             <table width=100% height=\"26\" border=0 align=\"center\" cellpadding=0 cellspacing=0>\n";
  echo "               <tr>\n";
  echo "                 <td width=\"15\" valign=\"top\" background=\"themes/XD-Obstuse/images/TBL/XD-Obstuso_TBL_09.gif\"><img src=\"themes/XD-Obstuse/images/TBL/XD-Obstuso_TBL_09.gif\" width=15 height=1 alt=\"\"></td>\n";
  echo "                 <td bgcolor=\"#151515\"><div align=\"center\"><font face=verdana,arial,helvetica size=1><font face=verdana,arial,helvetica size=1>$sitemsg </font></font></div></td>\n";
  echo "                 <td width=\"15\" valign=\"top\" background=\"themes/XD-Obstuse/images/TBL/XD-Obstuso_TBL_10.gif\"><div align=\"right\"><img src=\"themes/XD-Obstuse/images/TBL/XD-Obstuso_TBL_10.gif\" width=15 height=1 alt=\"\"></div></td>\n";
  echo "               </tr>\n";
  echo "             </table>\n";
  echo "             <table width=100% border=0 align=\"center\" cellpadding=0 cellspacing=0>\n";
  echo "               <tr>\n";
  echo "                 <td width=\"11\" valign=\"top\"><img src=\"themes/XD-Obstuse/images/TBL/XD-Obstuso_TBL_13.gif\" width=52 height=29 alt=\"\"></td>\n";
  echo "                 <td valign=\"top\" background=\"themes/XD-Obstuse/images/TBL/XD-Obstuso_TBL_15.gif\">&nbsp;</td>\n";
  echo "                 <td width=\"19\" valign=\"top\" background=\"\"><div align=\"right\"><img src=\"themes/XD-Obstuse/images/TBL/XD-Obstuso_TBL_17.gif\" width=58 height=29 alt=\"\"></div></td>\n";
  echo "               </tr>\n";
  echo "           </table></td>\n";
  echo "       </tr>\n";
  echo "   </table></td>\n";
  echo "   <td width=\"28\" background=\"themes/XD-Obstuse/images/XD-Obstuso_LEFT.gif\"> <img src=\"themes/XD-Obstuse/images/XD-Obstuso_LEFT.gif\" width=\"28\" height=\"1\"></td>\n";
  echo " </tr>\n";
echo "</TABLE>\n";
?>