<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 22 Oct 2008 11:00:15 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  '' => 
  array (
  ),
);

?>