<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 22 Oct 2008 11:00:18 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'latest' => '4.0',
  'lastCheck' => 1224673218,
);

?>