<?php

echo "<table id=\"Table_01\" width=\"100%\" height=\"209\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">";
echo "	<tr>";
echo "		<td rowspan=\"6\">";
echo "			<img src=\"themes/S-GRaw/images/fr_01.png\" width=\"38\" height=\"209\" alt=\"\"></td>";
echo "		<td colspan=\"4\">";
echo "			<img src=\"themes/S-GRaw/images/fr_02.png\" width=\"230\" height=\"35\" alt=\"\"></td>";
echo "		<td rowspan=\"6\">";
echo "			<img src=\"themes/S-GRaw/images/fr_03.png\" width=\"25\" height=\"209\" alt=\"\"></td>";
echo "		<td rowspan=\"6\" background=\"themes/S-GRaw/images/fr_04.png\" width=\"100%\" height=\"209\">&nbsp;</td>";
echo "		<td rowspan=\"4\">";
echo "			<img src=\"themes/S-GRaw/images/fr_05.png\" width=\"248\" height=\"86\" alt=\"\"></td>";
echo "		<td colspan=\"3\" rowspan=\"2\">";
echo "			<img src=\"themes/S-GRaw/images/fr_06.png\" width=\"220\" height=\"59\" alt=\"\"></td>";
echo "		<td rowspan=\"6\">";
echo "			<img src=\"themes/S-GRaw/images/fr_07.png\" width=\"37\" height=\"209\" alt=\"\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"35\" alt=\"\"></td>";
echo "	</tr>";
echo "	<tr>";
echo "		<td rowspan=\"2\">";
echo "			<a href=\"index.php\"><img src=\"themes/S-GRaw/images/fr_08.png\" width=\"58\" height=\"35\" border=\"0\"></td>";
echo "		<td rowspan=\"2\">";
echo "			<a href=\"modules.php?name=Downloads\"><img src=\"themes/S-GRaw/images/fr_09.png\" width=\"56\" height=\"35\" border=\"0\"></td>";
echo "		<td rowspan=\"2\">";
echo "			<a href=\"modules.php?name=Forums\"><img src=\"themes/S-GRaw/images/fr_10.png\" width=\"54\" height=\"35\" border=\"0\"></td>";
echo "		<td rowspan=\"2\">";
echo "			<a href=\"modules.php?name=Your_Account\"><img src=\"themes/S-GRaw/images/fr_11.png\" width=\"62\" height=\"35\" border=\"0\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"24\" border=\"0\"></td>";
echo "	</tr>";
echo "	<tr>";
echo "		<td rowspan=\"4\">";
echo "			<img src=\"themes/S-GRaw/images/fr_12.png\" width=\"44\" height=\"150\" alt=\"\"></td>";
echo "		<td rowspan=\"2\">";
echo "			<img src=\"themes/S-GRaw/images/fr_13.png\" width=\"147\" height=\"27\" alt=\"\"></td>";
echo "		<td rowspan=\"4\">";
echo "			<img src=\"themes/S-GRaw/images/fr_14.png\" width=\"29\" height=\"150\" alt=\"\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"11\" alt=\"\"></td>";
echo "	</tr>";
echo "	<tr>";
echo "		<td colspan=\"4\" rowspan=\"3\">";
echo "			<img src=\"themes/S-GRaw/images/fr_15.png\" width=\"230\" height=\"139\" alt=\"\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"16\" alt=\"\"></td>";
echo "	</tr>";
echo "	<tr>";
echo "		<td background=\"themes/S-GRaw/images/fr_16.png\" width=\"248\" height=\"103\" alt=\"\">";
echo "		<div align=\"center\"><span class=\"footmsg\">$foot1 <br> $foot2</span></div>";
echo "		</td>";
echo "		<td background=\"themes/S-GRaw/images/fr_17.png\" width=\"100%\" height=\"103\" alt=\"\">$showdl</td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"103\" alt=\"\"></td>";
echo "	</tr>";
echo "	<tr>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/fr_18.png\" width=\"248\" height=\"20\" alt=\"\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/fr_19.png\" width=\"147\" height=\"20\" alt=\"\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"20\" alt=\"\"></td>";
echo "	</tr>";
echo "</table>";
?>