<?php

echo "<table id=\"Table_01\" width=\"100%\" height=\"250\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">";
echo "	<tr>";
echo "		<td rowspan=\"6\">";
echo "			<img src=\"themes/S-GRaw/images/header_01.png\" width=\"41\" height=\"250\" alt=\"\"></td>";
echo "		<td rowspan=\"3\">";
echo "			<img src=\"themes/S-GRaw/images/header_02.png\" width=\"174\" height=\"185\" alt=\"\"></td>";
echo "		<td rowspan=\"6\" background=\"themes/S-GRaw/images/header_03.png\" width=\"50%\" height=\"250\" alt=\"\">&nbsp;</td>";
echo "		<td colspan=\"4\">";
echo "			<img src=\"themes/S-GRaw/images/header_04.png\" width=\"360\" height=\"41\" alt=\"\"></td>";
echo "		<td rowspan=\"6\" background=\"themes/S-GRaw/images/header_05.png\" width=\"50%\" height=\"250\" alt=\"\">&nbsp;</td>";
echo "		<td rowspan=\"6\">";
echo "			<img src=\"themes/S-GRaw/images/header_06.png\" width=\"3\" height=\"250\" alt=\"\"></td>";
echo "		<td rowspan=\"3\">";
echo "			<img src=\"themes/S-GRaw/images/header_07.png\" width=\"168\" height=\"185\" alt=\"\"></td>";
echo "		<td rowspan=\"6\">";
echo "			<img src=\"themes/S-GRaw/images/header_08.png\" width=\"43\" height=\"250\" alt=\"\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"41\" alt=\"\"></td>";
echo "	</tr>";
echo "	<tr>";
echo "		<td colspan=\"4\">";
echo "			<img src=\"themes/S-GRaw/images/header_09.png\" width=\"360\" height=\"111\" alt=\"\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"111\" alt=\"\"></td>";
echo "	</tr>";
echo "	<tr>";
echo "		<td rowspan=\"2\">";
echo "			<a href=\"index.php\"><img src=\"themes/S-GRaw/images/header_10.png\" width=\"98\" height=\"48\" alt=\"\" border=\"0\"></td>";
echo "		<td rowspan=\"2\">";
echo "			<a href=\"modules.php?name=Downloads\"><img src=\"themes/S-GRaw/images/header_11.png\" width=\"81\" height=\"48\" alt=\"\" border=\"0\"></td>";
echo "		<td rowspan=\"2\">";
echo "			<a href=\"modules.php?name=Forums\"><img src=\"themes/S-GRaw/images/header_12.png\" width=\"79\" height=\"48\" alt=\"\" border=\"0\"></td>";
echo "		<td rowspan=\"2\">";
echo "			<a href=\"modules.php?name=Your_Account\"><img src=\"themes/S-GRaw/images/header_13.png\" width=\"102\" height=\"48\" alt=\"\" border=\"0\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"33\" alt=\"\"></td>";
echo "	</tr>";
echo "	<tr>";
echo "		<td rowspan=\"2\" background=\"themes/S-GRaw/images/header_14.png\" width=\"174\" height=\"24\" alt=\"\">";
echo "					<marquee direction=\"left\" behavior=\"scroll\" scroll=\"continuous\" scrollamount=\"5\" width=\"168\" height=\"13\" style=\"font-size:9px;color:#239FA1;font-family:verdana;\">YOUR FIRST MESSAGE HERE!!!!</marquee></TD>";
echo "		<td rowspan=\"2\" background=\"themes/S-GRaw/images/header_15.png\" width=\"168\" height=\"24\" alt=\"\">";
echo "					<marquee direction=\"left\" behavior=\"scroll\" scroll=\"continuous\" scrollamount=\"5\" width=\"168\" height=\"13\" style=\"font-size:9px;color:#239FA1;font-family:verdana;\">YOUR SECOND MESSAGE HERE!!!!</marquee></TD>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"15\" alt=\"\"></td>";
echo "	</tr>";
echo "	<tr>";
echo "		<td colspan=\"4\" rowspan=\"2\">";
echo "			<img src=\"themes/S-GRaw/images/header_16.png\" width=\"360\" height=\"50\" alt=\"\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"9\" alt=\"\"></td>";
echo "	</tr>";
echo "	<tr>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/header_17.png\" width=\"174\" height=\"41\" alt=\"\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/header_18.png\" width=\"168\" height=\"41\" alt=\"\"></td>";
echo "		<td>";
echo "			<img src=\"themes/S-GRaw/images/spacer.gif\" width=\"1\" height=\"41\" alt=\"\"></td>";
echo "	</tr>";
echo "</table>";

?>