<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Ecco Eventos</title>
<style type="text/css">
<!--
body {
	background-color: #000;
}
.fontes {
	font-family: Tahoma, Geneva, sans-serif; font-size:11px; color:#FFF
}
-->
</style></head>

<body><div align="center"><SCRIPT src="carrega.js"></SCRIPT>
                      <SCRIPT language=javascript>
     carregaFlash('intro.swf','800','600'); 
    </SCRIPT></div><br />
<table width="600" border="0" align="center">
  <tr>
    <td><div align="justify"><span class="fontes"><strong><div align="center">ESCLARESCIMENTO ECCO EVENTOS</div></strong><br />
      <br /><br />
      MOTIVADOS EM ATENDER A CARÊNCIA DE UM ESPAÇO PARA REALIZAÇÃO DE PEQUENAS FESTAS, ATÉ MEGA SHOWS, A EMPRESÁRIA ELAINE E SEU ESPOSO ELEOMAR LUIS LAVARDA, JUNTAMENTE COM JORGE LUIS MARCON E PEDRO LUIZ CANELLAS, DERAM VIDA À ECCO EVENTOS, NA CIDADE DE FREDERICO WESTPHALEN. <br /><br />
      NÃO FORAM MEDIDOS ESFORÇOS, NEM TÃO POUCO QUESTIONADAS AS EXIGÊNCIAS QUE LHES FORAM FEITAS PARA QUE FINALMENTE A CASA VIESSE A FUNCIONAR, ATENDENDO ÀS DETERMINAÇOES LEGAIS MUNICIPAIS, ESTADUAIS E FEDERAIS, GARANTINDO, ASSIM, CONFORTO E SEGURANÇA A TODOS QUE À ECCO EVENTOS VIESSEM A FREQUENTAR. <br /><br />
      MOVIDOS PELA CERTEZA DE ESTAR NO LUGAR PERFEITO PARA A REALIZAÇÃO DOS EVENTOS, SEM PERTURBAR A POPULAÇÃO COM POLUIÇÃO SONORA E AINDA, POR SER UM LUGAR PRÓXIMO DA CIDADE, MAS EM MEIO A MATA NATIVA, SEGUIRAM EM FRENTE, RESPEITANDO UM PROJETO MINUNCIOSO. SEMPRE COM O INTUITO DE NENHUMA LEI OU DIREITO INFRINGIR. <br /><br />
      UM PROJETO PENSADO, ONDE NÃO HÁ DEGRAUS E RAMPAS DE ACESSO, COM TRÁFEGO LIVRE A CADEIRANTES, COM PORTA ANTI-PÂNICO, HIDRANTES, RESERVATÓRIO DE ÁGUA, CAPTAÇÃO DE ÁGUA DO TELHADO PARA USO DE LIMPEZA E CONSUMO DE SEUS 33 SANITÁRIOS, LÂMPADAS DE EMERGÊNCIA, EXTINTORES, COZINHAS QUE ATENDEM AOS PADRÕES DE HIGIENE E CONFORTO À EQUIPE QUE NELA FOR TRABALHAR, ENTRE OUTROS. <br /><br />
      A ECCO EVENTOS MOVIMENTA VARIOS EMPREGOS DIRETOS E INDIRETOS. EM NOSSO ESTABELECIMENTO PROPORCIONAMOS TRABALHO PARA: EQUIPES DE DECORAÇÕES, EQUIPES DE GARÇONS, EQUIPES DE SEGURANÇAS, EQUIPE DE FOTOGRAFOS, EQUIPES DE FILMAGENS, EQUIPES DE SOM E LUZES, EQUIPES DE CULINÁRIA, EQUIPES DE PESSOAS RESPONSÁVEIS PELA LIMPEZA ANTES E APÓS CADA EVENTO, EQUIPE DE JARDINAGEM E OUTROS. <br /><br />
      O QUE ESPERAMOS EM TROCA DE TUDO ISSO? QUE O MESMO RESPEITO E CONSIDERAÇÃO QUE TIVEMOS COM TODA A SOCIEDADE LOCAL SEJA A NÓS RETRIBUÍDO, DE FORMA CORDIAL E SEM PERSEGUIÇÕES ESPECÍFICAS. <br /><br />
      COM RELAÇÃO AO ÚLTIMO EVENTO CELEBRADO (SHOW DA BANDA JOTA QUEST E OUTROS), VIMOS POR MEIO DESTE MANIFESTAR UM DESCONTENTAMENTO COM A ATUAÇÃO E FISCALIZAÇÃO PROMOVIDA PELA POLÍCIA RODOVIÁRIA FEDERAL, EM LOCAL PRÓXIMO À ENTRADA PRINCIPAL DA ECCO. <br /><br />
      NÃO QUESTIONAMOS A IMPORTÂNCIA DA FISCALIZAÇÃO, MUITO MENOS O MÉTODO DE ATUAÇÃO, SENDO QUE SOMOS TOTALMENTE FAVORÁVEIS A ISTO, PORÉM, QUESTIONAMOS A PRESENÇA DE TAIS AGENTES PÚBLICOS SOMENTE EM EVENTOS PROMOVIDOS PELA ECCO, SENDO QUE NÃO PERCEBEMOS QUALQUER COMOÇÃO DOS ORGÃOS POLÍCIAS EM OUTROS EVENTOS QUE NÃO PROMOVIDOS PELA NOSSA CASA. <br /><br />
      CONCORDAMOS QUE A FISCALIZAÇÃO CUMPRA SEU DEVER, MAS QUE SEJA EM TODOS OS ESTABELECIMENTOS, INDEPENDENTEMENTE DA COMPETÊNCIA FUNCIONAL DE CADA POLÍCIA PREVENTIVA, POIS A ECCO PREOCUPA-SE COM O BEM-ESTAR DE SEUS FREQUENTADORES, SEMPRE NOTICIANDO O EVENTO AOS ÓRGAOS COMPETENTES PARA, ASSIM, REALIZAREM A FISCALIZAÇÃO COM ÊXITO, DIFERENTEMENTE DO QUE SE OBSERVA EM EVENTOS REALIZADOS NA ÁREA URBANA DE NOSSO MUNICÍPIO. <br /><br />
      A ECCO PREOCUPA-SE POR DEMAIS COM SEUS FREQUENTADORES, TANTO QUE ESTÁ SE ORGANIZANDO PARA NOS PRÓXIMOS EVENTOS DEIXAR UM TRANSPORTE À DISPOSIÇÃO ÀQUELES QUE TIVEREM INTERESSE EM UTILIZAR-SE DE TAL SERVIÇO. <br /><br />
      SENDO ASSIM, PEDIDOS PARA QUE AS AUTORIDADES PREZEM PELA SEGURANÇA E TRANQÜILIDADE DE TODOS OS FREQÜENTADORES DE SHOWS E EVENTOS PÚBLICOS, INDEPENDENTEMENTE DA CASA QUE O CELEBRAR, SEMPRE ATUANDO COM FIRMEZA E RESPONSABILIDADE. 
    </span><br />
    </div></td>
  </tr>
</table>
<p>&nbsp;</p>
</body>
</html>