<!--#include file="bd.inc"-->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD><TITLE>Administra&ccedil;&atilde;o dos pedidos de m&uacute;sicas Radio Luz e Alegria</TITLE>
<META http-equiv=Content-Type content="text/html; charset=iso-8859-1">
<LINK href="Radio95.9FM_arquivos/default.css" type=text/css rel=STYLESHEET>
<!--Code generated by Cool Web Scrollbars from Harmony Hollow Software-->
<!--http://www.harmonyhollow.net-->
<STYLE type="text/css">
<!--
BODY {
scrollbar-face-color:#0080C0;
scrollbar-highlight-color:#0080C0;
scrollbar-3dlight-color:#454545;
scrollbar-darkshadow-color:#454545;
scrollbar-shadow-color:#454545;
scrollbar-arrow-color:#FFFFFF;
scrollbar-track-color:#454545;
}
-->
</STYLE>
<!--End Cool Web Scrollbars code-->

<META content="MSHTML 6.00.2600.0" name=GENERATOR></HEAD>
<BODY bgColor=#EAEDF4 text="#000000" link="#000000" vlink="#000000" alink="#000000" leftMargin=0 topMargin=0 marginwidth="0" marginheight="0">
<font size="1" face="Verdana, Arial, Helvetica, sans-serif"> </font> 
<div align="center">
<p><font color="#000000" size="2" face="Verdana, Arial, Helvetica, sans-serif"><img src="fundofm.jpg" width="280" height="201"></font></p>
  <p><font color="#000000" size="3" face="Verdana, Arial, Helvetica, sans-serif">Locutores</font></p>
  <p><font color="#000000" size="2" face="Verdana, Arial, Helvetica, sans-serif">Aqui ser&atilde;o 
    postadas as m&uacute;sicas pelos ouvintes...</font></p>
  <p><font color="#000000" size="2" face="Verdana, Arial, Helvetica, sans-serif"><a href="upload2.asp">Clique 
    aqui para atualizar!</a></font>
    <%
ler.MoveFirst
DO WHILE NOT ler.EOF
%>
    <%
nome = ler("nome")
url = ler("url")
id = ler("id")
msg = ler("msg")
email = ler("email")
ip = ler("ip")
data = ler("data")
hora = ler("hora")
%>
  </p>
  <table width="70%" border="0" align="left" bordercolorlight="#99CC66" bordercolordark="#99CC66">
    <tr bgcolor="#292929"> 
      <td bgcolor="#EAEDF4"> 
        <div align="center"> 
          <p align="left"><font color="#000000" size="1" face="Verdana, Arial, Helvetica, sans-serif">Nome:<%=nome%> 
            </font></p>
          <p align="left"><font color="#000000" size="1" face="Verdana, Arial, Helvetica, sans-serif">M&uacute;sica</font></p>
          <p align="left"><font color="#000000" size="1" face="Verdana, Arial, Helvetica, sans-serif"> 
            <%=email%> 
            <%if url <> "" then%>
            :::|::: <a href="<%=url%>" target="blablabla"><%=url%></a> 
            <%end if%>
            </font></p>
          <p align="left">&nbsp;</p>
        </div></td>
    </tr>
    <tr bgcolor="#99CC66"> 
      <td bgcolor="EAEDF4"> 
        <div align="left"><font color="#000000" size="1" face="Verdana, Arial, Helvetica, sans-serif">
          <% sqv = "SELECT * FROM c_guest_cont WHERE email = '"& email &"'"
set v = c.execute(sqv)
v = v("vezes") %>
          </font></div></td>
    </tr>
    <tr bgcolor="#99CC66"> 
      <td bgcolor="#EAEDF4"> 
        <div align="center"> 
          <p><font color="#000000" size="1" face="Verdana, Arial, Helvetica, sans-serif">Para...</font></p>
        </div></td>
    </tr>
    <tr bgcolor="#99CC66"> 
      <td bgcolor="EAEDF4"> 
        <div align="center"> 
          <p><font color="#000000" size="1" face="Verdana, Arial, Helvetica, sans-serif"><%=msg%> 
            </font></p>
          <hr color="#0099CC">
          <p>&nbsp;</p>
        </div></td>
    </tr>
  </table>
  <%ler.MoveNext%>
  <%loop%>
  <p>&nbsp; </p>
</div>
</BODY></HTML>
