#
# Table structure for table judaslanguages
#

CREATE TABLE `judaslanguages` (
  `id` bigint(20) NOT NULL auto_increment,
  `LANGID` varchar(15) NOT NULL default '',
  `TEXTID` varchar(30) NOT NULL default '',
  `TEXT` varchar(255) NOT NULL default '',
  UNIQUE KEY `id` (`id`),
  KEY `LANGID` (`LANGID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='CRM language table';

#
# Dumping data for table judaslanguages
#

INSERT INTO `judaslanguages` VALUES (1,'PORTUGUES','customer','Cliente\n');
INSERT INTO `judaslanguages` VALUES (2,'PORTUGUES','owner','Dono\n');
INSERT INTO `judaslanguages` VALUES (3,'PORTUGUES','entity','tarefa\n');
INSERT INTO `judaslanguages` VALUES (4,'PORTUGUES','priority','Prioridade\n');
INSERT INTO `judaslanguages` VALUES (5,'PORTUGUES','assignee','Responsável\n');
INSERT INTO `judaslanguages` VALUES (6,'PORTUGUES','duedate','Para dia\n');
INSERT INTO `judaslanguages` VALUES (7,'PORTUGUES','alarmdate','Data do Alarme\n');
INSERT INTO `judaslanguages` VALUES (8,'PORTUGUES','alarmdatev','Criar alarme para esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (9,'PORTUGUES','category','Categoria\n');
INSERT INTO `judaslanguages` VALUES (10,'PORTUGUES','status','Status\n');
INSERT INTO `judaslanguages` VALUES (11,'PORTUGUES','helpcontents','Tópicos de ajuda\n');
INSERT INTO `judaslanguages` VALUES (12,'PORTUGUES','tolimited','Devido a falta de privilégios você foi direcionado para uma tela limitada\n');
INSERT INTO `judaslanguages` VALUES (13,'PORTUGUES','briefover','Relatório sobre a tarefa\n');
INSERT INTO `judaslanguages` VALUES (14,'PORTUGUES','mightbebetter','Seria melhor você usar a opção de relatório\n');
INSERT INTO `judaslanguages` VALUES (15,'PORTUGUES','editthis','Edite esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (16,'PORTUGUES','alarmsettings','Opções do Alarme\n');
INSERT INTO `judaslanguages` VALUES (17,'PORTUGUES','closethisentity','Fechar esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (18,'PORTUGUES','deletethisentity','Deletar esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (19,'PORTUGUES','downloadpdf','Baixar relatório em PDF sobre esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (20,'PORTUGUES','downloadpdfs','Baixar relatório em PDF\n');
INSERT INTO `judaslanguages` VALUES (21,'PORTUGUES','close','Fechar\n');
INSERT INTO `judaslanguages` VALUES (22,'PORTUGUES','edit','Editar\n');
INSERT INTO `judaslanguages` VALUES (23,'PORTUGUES','delete','Deletar\n');
INSERT INTO `judaslanguages` VALUES (24,'PORTUGUES','pdfreport','Relatório em PDF\n');
INSERT INTO `judaslanguages` VALUES (25,'PORTUGUES','welcome1','Bem-vindo ao\n');
INSERT INTO `judaslanguages` VALUES (26,'PORTUGUES','intro1','Esta ferramenta é usada para grava as dúvidas dos clientes. Agora eles são\n');
INSERT INTO `judaslanguages` VALUES (27,'PORTUGUES','intro2','usuários registrados,<br>que no total são\n');
INSERT INTO `judaslanguages` VALUES (28,'PORTUGUES','intro3','tarefas logadas, para\n');
INSERT INTO `judaslanguages` VALUES (29,'PORTUGUES','intro4','clientes.\n');
INSERT INTO `judaslanguages` VALUES (30,'PORTUGUES','welcome','Bem-vindo\n');
INSERT INTO `judaslanguages` VALUES (31,'PORTUGUES','lastlogon','Última vez que logou\n');
INSERT INTO `judaslanguages` VALUES (32,'PORTUGUES','entitiestoday','tarefas para hoje\n');
INSERT INTO `judaslanguages` VALUES (33,'PORTUGUES','noentities','Não há nenhuma tarefa para hoje\n');
INSERT INTO `judaslanguages` VALUES (34,'PORTUGUES','gotomainpage','Ir para a página principal\n');
INSERT INTO `judaslanguages` VALUES (35,'PORTUGUES','main','Principal\n');
INSERT INTO `judaslanguages` VALUES (36,'PORTUGUES','addcusttodb','Adicionar o pedido do cliente na base de dados\n');
INSERT INTO `judaslanguages` VALUES (37,'PORTUGUES','add','Adicionar\n');
INSERT INTO `judaslanguages` VALUES (38,'PORTUGUES','viewbrief','Ver um relatório das tarefas gravadas na base de dados\n');
INSERT INTO `judaslanguages` VALUES (39,'PORTUGUES','entities','Tarefas\n');
INSERT INTO `judaslanguages` VALUES (40,'PORTUGUES','brieflistdel','Ver um relatório das tarefas apagadas da base de dados\n');
INSERT INTO `judaslanguages` VALUES (41,'PORTUGUES','delentities','Deletar tarefas\n');
INSERT INTO `judaslanguages` VALUES (42,'PORTUGUES','vacoa','Ver, adicionar ou mudar possíveis donos ou Responsávels\n');
INSERT INTO `judaslanguages` VALUES (43,'PORTUGUES','oa','Donos/Responsávels\n');
INSERT INTO `judaslanguages` VALUES (44,'PORTUGUES','vacc','Ver, adicionar ou modificar clientes\n');
INSERT INTO `judaslanguages` VALUES (45,'PORTUGUES','customers','Clientes\n');
INSERT INTO `judaslanguages` VALUES (46,'PORTUGUES','dumpi','Eliminar as vírgulas para exportar os dados da base de dados\n');
INSERT INTO `judaslanguages` VALUES (47,'PORTUGUES','phonebook1','Agenda de Telefones\n');
INSERT INTO `judaslanguages` VALUES (48,'PORTUGUES','phonebookshort','AT\n');
INSERT INTO `judaslanguages` VALUES (49,'PORTUGUES','sumverb','Ver e imprimir relatórios mais avançados\n');
INSERT INTO `judaslanguages` VALUES (50,'PORTUGUES','summary','Relatório\n');
INSERT INTO `judaslanguages` VALUES (51,'PORTUGUES','logout','Sair\n');
INSERT INTO `judaslanguages` VALUES (52,'PORTUGUES','maninfo','Informações de Administração\n');
INSERT INTO `judaslanguages` VALUES (53,'PORTUGUES','maninfoverb','Relatórios de estatísticas para Administração\n');
INSERT INTO `judaslanguages` VALUES (54,'PORTUGUES','sitestats','Estatísticas do site\n');
INSERT INTO `judaslanguages` VALUES (55,'PORTUGUES','sitestatsverb','As estatísticas deste site\n');
INSERT INTO `judaslanguages` VALUES (56,'PORTUGUES','administration','Administração\n');
INSERT INTO `judaslanguages` VALUES (57,'PORTUGUES','administrationverb','Funçoes de Administração\n');
INSERT INTO `judaslanguages` VALUES (58,'PORTUGUES','helpcontentsverb','Mostrar lista de conteúdo da ajuda\n');
INSERT INTO `judaslanguages` VALUES (59,'PORTUGUES','dateinvalid','A data que você escolhe é inválida.n A data não foi escolhida.\n');
INSERT INTO `judaslanguages` VALUES (60,'PORTUGUES','entrysaved','Digitar número do pedido\n');
INSERT INTO `judaslanguages` VALUES (61,'PORTUGUES','wasadded','foi adicionado.\n');
INSERT INTO `judaslanguages` VALUES (62,'PORTUGUES','deleting1','Deletando\n');
INSERT INTO `judaslanguages` VALUES (63,'PORTUGUES','deleting2','arquivo(s). Aperte o botão abaixo para confirmar.\n');
INSERT INTO `judaslanguages` VALUES (64,'PORTUGUES','confdel','Confirme deletagem\n');
INSERT INTO `judaslanguages` VALUES (65,'PORTUGUES','deletingentity','Deletando tarefa\n');
INSERT INTO `judaslanguages` VALUES (66,'PORTUGUES','ownedby','pertence à\n');
INSERT INTO `judaslanguages` VALUES (67,'PORTUGUES','assignedto','Responsável para\n');
INSERT INTO `judaslanguages` VALUES (68,'PORTUGUES','curstat','Status atual\n');
INSERT INTO `judaslanguages` VALUES (69,'PORTUGUES','created','criado\n');
INSERT INTO `judaslanguages` VALUES (70,'PORTUGUES','lastupdate','última atualização\n');
INSERT INTO `judaslanguages` VALUES (71,'PORTUGUES','deleteerror','Você não pode deletar esta tarefa pois ela não foi terminada\n');
INSERT INTO `judaslanguages` VALUES (72,'PORTUGUES','confirmdel','Clique aqui para deletar esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (73,'PORTUGUES','search','Procura\n');
INSERT INTO `judaslanguages` VALUES (74,'PORTUGUES','thereare','São\n');
INSERT INTO `judaslanguages` VALUES (75,'PORTUGUES','openentities','Abrir tarefas\n');
INSERT INTO `judaslanguages` VALUES (76,'PORTUGUES','noopen','Não há tarefas abertas.\n');
INSERT INTO `judaslanguages` VALUES (77,'PORTUGUES','nonexistent','Você digitou um número de tarefa que não existe!\n');
INSERT INTO `judaslanguages` VALUES (78,'PORTUGUES','editing','Editando\n');
INSERT INTO `judaslanguages` VALUES (79,'PORTUGUES','wasclosed','Esta tarefa foi fechada\n');
INSERT INTO `judaslanguages` VALUES (80,'PORTUGUES','newentity','Nova tarefa\n');
INSERT INTO `judaslanguages` VALUES (81,'PORTUGUES','isdeleted','Esta é uma tarefa deletada\n');
INSERT INTO `judaslanguages` VALUES (82,'PORTUGUES','iswaiting','Aguardando outra pessoa\n');
INSERT INTO `judaslanguages` VALUES (83,'PORTUGUES','doesntbelonghere','Esta tarefa não pertence a este local\n');
INSERT INTO `judaslanguages` VALUES (84,'PORTUGUES','listofatt','Listar arquivos anexados a esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (85,'PORTUGUES','filename','Nome do arquivo\n');
INSERT INTO `judaslanguages` VALUES (86,'PORTUGUES','filesize','Tamanho\n');
INSERT INTO `judaslanguages` VALUES (87,'PORTUGUES','creationdate','Data de criação\n');
INSERT INTO `judaslanguages` VALUES (88,'PORTUGUES','deletefile','Deletar\n');
INSERT INTO `judaslanguages` VALUES (89,'PORTUGUES','attachfile','Anexar arquivo\n');
INSERT INTO `judaslanguages` VALUES (90,'PORTUGUES','saveclose','Salvar e Fechar\n');
INSERT INTO `judaslanguages` VALUES (91,'PORTUGUES','cancel','Cancelar\n');
INSERT INTO `judaslanguages` VALUES (92,'PORTUGUES','save','Salvar para base de dados\n');
INSERT INTO `judaslanguages` VALUES (93,'PORTUGUES','noaction','Erro, nenhuma ação escolhida\n');
INSERT INTO `judaslanguages` VALUES (94,'PORTUGUES','zailo','falta zero consignados\n');
INSERT INTO `judaslanguages` VALUES (95,'PORTUGUES','name','Nome\n');
INSERT INTO `judaslanguages` VALUES (96,'PORTUGUES','usrwarning','Se uma caixa está desabilitada (cinza), significa que seu dono ou responsável possui uma conta limitada, e portanto o nome não pode ser mudado<br>ou os dados podem ser perdidos.\n');
INSERT INTO `judaslanguages` VALUES (97,'PORTUGUES','ownassindb','Donos os responsáveis na base de dados\n');
INSERT INTO `judaslanguages` VALUES (98,'PORTUGUES','addownass','Adicionar dono/responsável\n');
INSERT INTO `judaslanguages` VALUES (99,'PORTUGUES','apply','Aplicar alterações\n');
INSERT INTO `judaslanguages` VALUES (100,'PORTUGUES','custindb','Clientes na base de dados\n');
INSERT INTO `judaslanguages` VALUES (101,'PORTUGUES','addcust','Adicionar um cliente\n');
INSERT INTO `judaslanguages` VALUES (102,'PORTUGUES','selectfields','Por favor selecionar os campos que deseja exportar\n');
INSERT INTO `judaslanguages` VALUES (103,'PORTUGUES','lastupdatedate','Data da última atualização\n');
INSERT INTO `judaslanguages` VALUES (104,'PORTUGUES','lastupdatetime','Hora da última atualização\n');
INSERT INTO `judaslanguages` VALUES (105,'PORTUGUES','closedate','Data de fechamento\n');
INSERT INTO `judaslanguages` VALUES (106,'PORTUGUES','waitingcsv','Aguardando\n');
INSERT INTO `judaslanguages` VALUES (107,'PORTUGUES','doesntcsv','Não pertence a este local\n');
INSERT INTO `judaslanguages` VALUES (108,'PORTUGUES','contents','Conteúdo\n');
INSERT INTO `judaslanguages` VALUES (109,'PORTUGUES','alreadyselected','<b>Sua requisição foi gravada</b>\n');
INSERT INTO `judaslanguages` VALUES (110,'PORTUGUES','sep','Separação com caracteres\n');
INSERT INTO `judaslanguages` VALUES (111,'PORTUGUES','scqp','Separado por ponto-vírgula (;) (recomendado)\n');
INSERT INTO `judaslanguages` VALUES (112,'PORTUGUES','cqp','Separado com dois pontos (:)\n');
INSERT INTO `judaslanguages` VALUES (113,'PORTUGUES','kqp','Separado com vírgula (,)\n');
INSERT INTO `judaslanguages` VALUES (114,'PORTUGUES','csvwarning','Quando a caixa de download aparecer, seleciona \\\'Abrir o arquivo no local atual\\\'.<br> Talvez a mesma janela reapareça, se aparecer clique em \\\"Abrir\\\" novamente. Isto deve abrir seu Excel <br>com os dados exportados.\n');
INSERT INTO `judaslanguages` VALUES (115,'PORTUGUES','downloadexport','Baixar arquivo exportado\n');
INSERT INTO `judaslanguages` VALUES (116,'PORTUGUES','repdownloaded','Relotório foi baixado\n');
INSERT INTO `judaslanguages` VALUES (117,'PORTUGUES','endofreport','Fim do relatório. Tenha um ótimo dia :)\n');
INSERT INTO `judaslanguages` VALUES (118,'PORTUGUES','noresults','Seu pedido não obteve nenhum resultado.\n');
INSERT INTO `judaslanguages` VALUES (119,'PORTUGUES','entitiesfound','tarefas encontradas.\n');
INSERT INTO `judaslanguages` VALUES (120,'PORTUGUES','pbexport','exportar agenda de telefones\n');
INSERT INTO `judaslanguages` VALUES (121,'PORTUGUES','endofpbexport','<red> -- Fim do Relatório --\n');
INSERT INTO `judaslanguages` VALUES (122,'PORTUGUES','pbexpmade','Arquivo de exportação da agenda de telefones criado\n');
INSERT INTO `judaslanguages` VALUES (123,'PORTUGUES','wasdeleted','foi deletado\n');
INSERT INTO `judaslanguages` VALUES (124,'PORTUGUES','pbdelconf','a que deseja apagar esta gravação?\n');
INSERT INTO `judaslanguages` VALUES (125,'PORTUGUES','fname','Primeiro nome\n');
INSERT INTO `judaslanguages` VALUES (126,'PORTUGUES','lname','Sobrenome\n');
INSERT INTO `judaslanguages` VALUES (127,'PORTUGUES','tel','Telefone\n');
INSERT INTO `judaslanguages` VALUES (128,'PORTUGUES','company','Empresa\n');
INSERT INTO `judaslanguages` VALUES (129,'PORTUGUES','dep','Departamento\n');
INSERT INTO `judaslanguages` VALUES (130,'PORTUGUES','title','Título\n');
INSERT INTO `judaslanguages` VALUES (131,'PORTUGUES','room','Quarto\n');
INSERT INTO `judaslanguages` VALUES (132,'PORTUGUES','deletepb','Deletar\n');
INSERT INTO `judaslanguages` VALUES (133,'PORTUGUES','pbrecadded','Seu contato foi adicionado na agenda de telefones.\n');
INSERT INTO `judaslanguages` VALUES (134,'PORTUGUES','pbapp','Suas alterações foram aplicadas.\n');
INSERT INTO `judaslanguages` VALUES (135,'PORTUGUES','pbwarning','Por favor preencha pelo menos o sobrenome!\n');
INSERT INTO `judaslanguages` VALUES (136,'PORTUGUES','addtopb','Adicionar a agenda de telefones\n');
INSERT INTO `judaslanguages` VALUES (137,'PORTUGUES','pbresults','Resultados para sua pesquisa\n');
INSERT INTO `judaslanguages` VALUES (138,'PORTUGUES','options','Opções\n');
INSERT INTO `judaslanguages` VALUES (139,'PORTUGUES','resfound','resultados encontrados\n');
INSERT INTO `judaslanguages` VALUES (140,'PORTUGUES','pbcont1','Esta agenda de telefones contém\n');
INSERT INTO `judaslanguages` VALUES (141,'PORTUGUES','pbcont2','contatos\n');
INSERT INTO `judaslanguages` VALUES (142,'PORTUGUES','pbaddrec','adicionar contato\n');
INSERT INTO `judaslanguages` VALUES (143,'PORTUGUES','entsum','Relatório de tarefas\n');
INSERT INTO `judaslanguages` VALUES (144,'PORTUGUES','showonly','Mostra apenas\n');
INSERT INTO `judaslanguages` VALUES (145,'PORTUGUES','all','Tudo\n');
INSERT INTO `judaslanguages` VALUES (146,'PORTUGUES','inccont','Adicionar comentários a tarefa\n');
INSERT INTO `judaslanguages` VALUES (147,'PORTUGUES','incldel','Incluir tarefas excluidas\n');
INSERT INTO `judaslanguages` VALUES (148,'PORTUGUES','dlacsv','Baixar resultado como CSV\n');
INSERT INTO `judaslanguages` VALUES (149,'PORTUGUES','briefo','Dados resumidos\n');
INSERT INTO `judaslanguages` VALUES (150,'PORTUGUES','mustcontain','Tarefa deve conter texto\n');
INSERT INTO `judaslanguages` VALUES (151,'PORTUGUES','please','Por favor faça sua escolha...\n');
INSERT INTO `judaslanguages` VALUES (152,'PORTUGUES','remarks','Remarcar\n');
INSERT INTO `judaslanguages` VALUES (153,'PORTUGUES','hasfilessum','Esta tarefa possui arquivos anexados\n');
INSERT INTO `judaslanguages` VALUES (154,'PORTUGUES','expired','A data de realização desta tarefa expirou!\n');
INSERT INTO `judaslanguages` VALUES (155,'PORTUGUES','thisiswaiting','Esta tarefa está aguardando ação de outra pessoa.\n');
INSERT INTO `judaslanguages` VALUES (156,'PORTUGUES','thisdoesntbelong','Este tarefa realmente não pertence a este local\n');
INSERT INTO `judaslanguages` VALUES (157,'PORTUGUES','clear','limpar\n');
INSERT INTO `judaslanguages` VALUES (158,'PORTUGUES','wrongpwd','Senha incorreta. Por favor tente novamente ou se mande\n');
INSERT INTO `judaslanguages` VALUES (159,'PORTUGUES','havetoenterpwd','Visto que sua conta não possui privilégios de administrador, você terá que colocar a senha de administrador\n');
INSERT INTO `judaslanguages` VALUES (160,'PORTUGUES','adm','Administração\n');
INSERT INTO `judaslanguages` VALUES (161,'PORTUGUES','nopwd','Visto que sua conta tem privilégios de administrador, a senha para o mesmo não foi pedida.\n');
INSERT INTO `judaslanguages` VALUES (162,'PORTUGUES','imported','print \\\"Foram $imported gravaçoes importadas.\\\";\n');
INSERT INTO `judaslanguages` VALUES (163,'PORTUGUES','ignored','gravaçoes foram ignoradas por conter um campo vazio.\n');
INSERT INTO `judaslanguages` VALUES (164,'PORTUGUES','impwarning','Para impedir que uma gravação seja importada, esvazie o campo \\\"Nome\\\". Corrija os que estiverem errados.\n');
INSERT INTO `judaslanguages` VALUES (165,'PORTUGUES','commawarning','Visto que você escolheu importar um arquivo separado por vírgulas, fique atento com combinações do tipo sobrenome, nome (que são comuns no Outlook) que podem produzir efeitos indesejados.\n');
INSERT INTO `judaslanguages` VALUES (166,'PORTUGUES','importinpb','Importar dados da agenda de telefones\n');
INSERT INTO `judaslanguages` VALUES (167,'PORTUGUES','pbimpwarning','As informações CSV que você colou <i>devem</i> conter todos campos, contudo eles podem ser vazios:\n');
INSERT INTO `judaslanguages` VALUES (168,'PORTUGUES','paste','Cole seu texto aqui ...\n');
INSERT INTO `judaslanguages` VALUES (169,'PORTUGUES','pleasechoose','Por favor selecione uma das opções abaixo:\n');
INSERT INTO `judaslanguages` VALUES (170,'PORTUGUES','chgsys','Trocar valores do sistema\n');
INSERT INTO `judaslanguages` VALUES (171,'PORTUGUES','impphone','Importar dadso da agenda de telefones\n');
INSERT INTO `judaslanguages` VALUES (172,'PORTUGUES','viewfiles','Ver arquivos na base de dados\n');
INSERT INTO `judaslanguages` VALUES (173,'PORTUGUES','delallclosed','Deletar todas as tarefas concluídas\n');
INSERT INTO `judaslanguages` VALUES (174,'PORTUGUES','eahelp','Adicionar/Editar tópicos de ajuda\n');
INSERT INTO `judaslanguages` VALUES (175,'PORTUGUES','physdel','Deletar fisicamente uma tarefa deletada\n');
INSERT INTO `judaslanguages` VALUES (176,'PORTUGUES','viewlog','Ver logs e estatísticas\n');
INSERT INTO `judaslanguages` VALUES (177,'PORTUGUES','manacc','Administrar contas\n');
INSERT INTO `judaslanguages` VALUES (178,'PORTUGUES','isdel','foi deletado\n');
INSERT INTO `judaslanguages` VALUES (179,'PORTUGUES','delfile','Deletando arquivo fisicamente\n');
INSERT INTO `judaslanguages` VALUES (180,'PORTUGUES','physdelwarning','Por favor digite o ID da tarefa<b>fechada e deletada</b> que você quer <b>fisicamente</b> deletar:\n');
INSERT INTO `judaslanguages` VALUES (181,'PORTUGUES','confphysdel','Clique no botão abaixo para confirmar deletação física.\n');
INSERT INTO `judaslanguages` VALUES (182,'PORTUGUES','addhelp','Adicionar opção de ajuda:\n');
INSERT INTO `judaslanguages` VALUES (183,'PORTUGUES','editaccount','Editar uma conta\n');
INSERT INTO `judaslanguages` VALUES (184,'PORTUGUES','addaccount','Adicionar uma conta\n');
INSERT INTO `judaslanguages` VALUES (185,'PORTUGUES','password','Senha\n');
INSERT INTO `judaslanguages` VALUES (186,'PORTUGUES','addu','Adicionar Usuário\n');
INSERT INTO `judaslanguages` VALUES (187,'PORTUGUES','btmap','Voltar para a página principal do Administrador\n');
INSERT INTO `judaslanguages` VALUES (188,'PORTUGUES','passwarn','deixe os dois campos em branco para manter a senha atual\n');
INSERT INTO `judaslanguages` VALUES (189,'PORTUGUES','limited','Limitado\n');
INSERT INTO `judaslanguages` VALUES (190,'PORTUGUES','normal','Normal\n');
INSERT INTO `judaslanguages` VALUES (191,'PORTUGUES','adminrights','Administrador\n');
INSERT INTO `judaslanguages` VALUES (192,'PORTUGUES','yes','Sim\n');
INSERT INTO `judaslanguages` VALUES (193,'PORTUGUES','no','Não\n');
INSERT INTO `judaslanguages` VALUES (194,'PORTUGUES','ela','Editando conta de login\n');
INSERT INTO `judaslanguages` VALUES (195,'PORTUGUES','dta','Deletar esta conta\n');
INSERT INTO `judaslanguages` VALUES (196,'PORTUGUES','passmatcherror','Senha não confere. Pressione \\\'voltar\\\' no seu navegador e tente novamente.\n');
INSERT INTO `judaslanguages` VALUES (197,'PORTUGUES','nimut','Ocorreu um erro!<br><br>Esta conta existe, mas ela<br>não se refere a nenhum usuário na base de dados para o qual possam ser designadas tarefas.<br><br>Verifique o nome tente novamente.\n');
INSERT INTO `judaslanguages` VALUES (198,'PORTUGUES','uwchala','Usuários que podem ter conta limitada\n');
INSERT INTO `judaslanguages` VALUES (199,'PORTUGUES','tawu','A conta foi atualizada\n');
INSERT INTO `judaslanguages` VALUES (200,'PORTUGUES','setting','Configurações\n');
INSERT INTO `judaslanguages` VALUES (201,'PORTUGUES','value','Valores\n');
INSERT INTO `judaslanguages` VALUES (202,'PORTUGUES','discription','Descrição\n');
INSERT INTO `judaslanguages` VALUES (203,'PORTUGUES','ocsvifb','Ou troque os valores do sistema no formulário abaixo\n');
INSERT INTO `judaslanguages` VALUES (204,'PORTUGUES','csvnow','Troque os valores do sistema\n');
INSERT INTO `judaslanguages` VALUES (205,'PORTUGUES','plzenterpwd','Por favor digite a senha\n');
INSERT INTO `judaslanguages` VALUES (206,'PORTUGUES','eor','Fim do relatório\n');
INSERT INTO `judaslanguages` VALUES (207,'PORTUGUES','smtsm','Selecione mais para ver mais...\n');
INSERT INTO `judaslanguages` VALUES (208,'PORTUGUES','dlmspdf','ou clique aqui para baixar (mais compacto) um relatório em PDF\n');
INSERT INTO `judaslanguages` VALUES (209,'PORTUGUES','sts','Resumos a mostrar\n');
INSERT INTO `judaslanguages` VALUES (210,'PORTUGUES','oqs','Relatório Geral Resumido\n');
INSERT INTO `judaslanguages` VALUES (211,'PORTUGUES','eobu','Tarefas possuidas por usuários\n');
INSERT INTO `judaslanguages` VALUES (212,'PORTUGUES','eatu','Tarefas com usuários responsáveis\n');
INSERT INTO `judaslanguages` VALUES (213,'PORTUGUES','sae','Tarefas designadas para o mesmo usuário\n');
INSERT INTO `judaslanguages` VALUES (214,'PORTUGUES','etdbh','Tarefas que não pertencem a este local\n');
INSERT INTO `judaslanguages` VALUES (215,'PORTUGUES','ewfsea','Tarefas aguardando ação de outra pessoa\n');
INSERT INTO `judaslanguages` VALUES (216,'PORTUGUES','epc','Tarefas por Cliente\n');
INSERT INTO `judaslanguages` VALUES (217,'PORTUGUES','oepa','Tarefas expiradas, por usuário\n');
INSERT INTO `judaslanguages` VALUES (218,'PORTUGUES','deleted','Deletado\n');
INSERT INTO `judaslanguages` VALUES (219,'PORTUGUES','total','Total\n');
INSERT INTO `judaslanguages` VALUES (220,'PORTUGUES','ofwhich','das quais\n');
INSERT INTO `judaslanguages` VALUES (221,'PORTUGUES','allround','Todos valores sõa aproximados\n');
INSERT INTO `judaslanguages` VALUES (222,'PORTUGUES','atac','ou muito aproximados\n');
INSERT INTO `judaslanguages` VALUES (223,'PORTUGUES','edd','Datas de expiração\n');
INSERT INTO `judaslanguages` VALUES (224,'PORTUGUES','dontbelonghere','Tarefas que não pertencem a este local\n');
INSERT INTO `judaslanguages` VALUES (225,'PORTUGUES','eatw','Tarefas adicionadas esta semana\n');
INSERT INTO `judaslanguages` VALUES (226,'PORTUGUES','ectw','Tarefas concluídas esta semana\n');
INSERT INTO `judaslanguages` VALUES (227,'PORTUGUES','eatm','Tarefas adicionadas neste mês\n');
INSERT INTO `judaslanguages` VALUES (228,'PORTUGUES','ectm','Tarefas concluídas neste mês\n');
INSERT INTO `judaslanguages` VALUES (229,'PORTUGUES','of','De\n');
INSERT INTO `judaslanguages` VALUES (230,'PORTUGUES','tad','tarefas contadas, uma média total \\\'de realização\\\' desde a adição de uma tarefa até seu fechamento\n');
INSERT INTO `judaslanguages` VALUES (231,'PORTUGUES','cuaeoay','Contados usando <u>todas</u> tarefas concluídas da base de dados, ao longo de <u>todos</u> os anos\n');
INSERT INTO `judaslanguages` VALUES (232,'PORTUGUES','users','Usuários\n');
INSERT INTO `judaslanguages` VALUES (233,'PORTUGUES','customers','Clientes\n');
INSERT INTO `judaslanguages` VALUES (234,'PORTUGUES','zoilo','zero donos estão faltando\n');
INSERT INTO `judaslanguages` VALUES (235,'PORTUGUES','ombla','Ou : ou talvez tarefas que não tem responsáveis ou não foram designadas(...)\n');
INSERT INTO `judaslanguages` VALUES (236,'PORTUGUES','andassignee','e designadas\n');
INSERT INTO `judaslanguages` VALUES (237,'PORTUGUES','selfassig','Auto-Designadas\n');
INSERT INTO `judaslanguages` VALUES (238,'PORTUGUES','aohnsae','Outros donos não possuem tarefas auto-designadas.\n');
INSERT INTO `judaslanguages` VALUES (239,'PORTUGUES','onavarage','Em média\n');
INSERT INTO `judaslanguages` VALUES (240,'PORTUGUES','oaoedbh','de todas tarefas <b>abertas</b> não pertencem a este local\n');
INSERT INTO `judaslanguages` VALUES (241,'PORTUGUES','teaair','A tarefa e todas as sua anotações foram fisicamente deletadas\n');
INSERT INTO `judaslanguages` VALUES (242,'PORTUGUES','cookiewarning','Não use esta função em computadores públicos!\n');
INSERT INTO `judaslanguages` VALUES (243,'PORTUGUES','username','Usuário\n');
INSERT INTO `judaslanguages` VALUES (244,'PORTUGUES','saveusername','Lembrar usuário\n');
INSERT INTO `judaslanguages` VALUES (245,'PORTUGUES','clearusername','Esquecer usuário\n');
INSERT INTO `judaslanguages` VALUES (246,'PORTUGUES','savepassword','Lmebrar senha\n');
INSERT INTO `judaslanguages` VALUES (247,'PORTUGUES','clearpassword','Esquecer senha\n');
INSERT INTO `judaslanguages` VALUES (248,'PORTUGUES','signedoff','Você foi deslogado. Por favor digite seu usuário e senha para entrar novamente\n');
INSERT INTO `judaslanguages` VALUES (249,'PORTUGUES','signedoffdue1','Você foi deslogado devido a\n');
INSERT INTO `judaslanguages` VALUES (250,'PORTUGUES','signedoffdue2','minutos de inatividade\n');
INSERT INTO `judaslanguages` VALUES (251,'PORTUGUES','sysmsg','O Administrador do sistema deixou uma mensagem para você\n');
INSERT INTO `judaslanguages` VALUES (252,'PORTUGUES','pleaseenter','Por favor digite seu usuário e senha\n');
INSERT INTO `judaslanguages` VALUES (253,'PORTUGUES','language','Língua\n');
INSERT INTO `judaslanguages` VALUES (254,'PORTUGUES','pushpdf','Baixar resultados em arquivo PDF\n');
INSERT INTO `judaslanguages` VALUES (255,'PORTUGUES','managementheader','Bem-vindo a interface de usuário limitado. você está no sistema como\n');
INSERT INTO `judaslanguages` VALUES (256,'PORTUGUES','oefm','Tarefas abertas para\n');
INSERT INTO `judaslanguages` VALUES (257,'PORTUGUES','showresults','Método do Relatório\n');
INSERT INTO `judaslanguages` VALUES (258,'PORTUGUES','verbose','Verbose\n');
INSERT INTO `judaslanguages` VALUES (259,'PORTUGUES','verbosewithcontents','Verbose com tópicos\n');
INSERT INTO `judaslanguages` VALUES (260,'PORTUGUES','briefsum','Resumo rápido\n');
INSERT INTO `judaslanguages` VALUES (261,'PORTUGUES','downloadsumpdf','Baixar resumo como arquivo PDF\n');
INSERT INTO `judaslanguages` VALUES (262,'PORTUGUES','downloadsumcsv','Baixar resumo em arquivo Excel\n');
INSERT INTO `judaslanguages` VALUES (263,'PORTUGUES','packman','Administrar pacotes de linguagem\n');
INSERT INTO `judaslanguages` VALUES (264,'PORTUGUES','openinnewwindow','Abrir em uma nova janela\n');
INSERT INTO `judaslanguages` VALUES (265,'PORTUGUES','delcust','Deletar este usuário (<b>nenhuma</b> confirmação será pedida)\n');
INSERT INTO `judaslanguages` VALUES (266,'PORTUGUES','nousers1','Não há donos / responsáveis configurados. Antes de começar a usar o CRM, você precisa adicionar pelo menos um. Clique em \\\'Donos/Responsáveis\\\' para adicionar possíveis donos ou responsáveis!\n');
INSERT INTO `judaslanguages` VALUES (267,'PORTUGUES','custhomepage','Homepage\n');
INSERT INTO `judaslanguages` VALUES (268,'PORTUGUES','custremarks','Remarcação\n');
INSERT INTO `judaslanguages` VALUES (269,'PORTUGUES','customeraddress','Endereço do cliente\n');
INSERT INTO `judaslanguages` VALUES (270,'PORTUGUES','contactemail','E-mail para contato\n');
INSERT INTO `judaslanguages` VALUES (271,'PORTUGUES','contactphone','Telefone para contato\n');
INSERT INTO `judaslanguages` VALUES (272,'PORTUGUES','contact','Contato\n');
INSERT INTO `judaslanguages` VALUES (273,'PORTUGUES','contacttitle','Título de contato (ex. Sr.)\n');
INSERT INTO `judaslanguages` VALUES (274,'PORTUGUES','custdelexplain','Este cliente não pode ser deletado pois tem tarefas que pertencem a eles\n');
INSERT INTO `judaslanguages` VALUES (275,'PORTUGUES','editextras','Editar valores extras\n');
INSERT INTO `judaslanguages` VALUES (276,'PORTUGUES','fieldname','Nome\n');
INSERT INTO `judaslanguages` VALUES (277,'PORTUGUES','iftynmvhpcysa','Se você acha que precisa de mais nomes aqui, por favor contate o administrador do seu CRM.\n');
INSERT INTO `judaslanguages` VALUES (278,'PORTUGUES','extrafields','Campos extras\n');
INSERT INTO `judaslanguages` VALUES (279,'PORTUGUES','uinw','Atualizar em nova janela\n');
INSERT INTO `judaslanguages` VALUES (280,'PORTUGUES','nocustomers1','Não há clientes configurados. Antes de usar o CRM, você precisa fazer isto. Clique no menu \\\'Clientes\\\' para adicionar pelo menos um cliente!\n');
INSERT INTO `judaslanguages` VALUES (281,'PORTUGUES','nousersandnocustomers1','Não há clientes nem possíveis Donos/Designados configurados. Antes que você possa usar o CRM, você precisa fazer isto. Clique no menu \\\'Clientes\\\' para adicionar pelo menos um cliente, e depois no menu \\\'Donos/Designados\\\' para adicionar pelo menos um pos');
INSERT INTO `judaslanguages` VALUES (282,'PORTUGUES','managerepositories','Administrar repositores\n');
INSERT INTO `judaslanguages` VALUES (283,'PORTUGUES','viewdelentities','Ver tarefas deletadas\n');
INSERT INTO `judaslanguages` VALUES (284,'PORTUGUES','viewinsertedentities','Tarefas adicionadas\n');
INSERT INTO `judaslanguages` VALUES (285,'PORTUGUES','readonly','Read-only\n');
INSERT INTO `judaslanguages` VALUES (286,'PORTUGUES','customer','Cliente\n');
INSERT INTO `judaslanguages` VALUES (287,'PORTUGUES','owner','Dono\n');
INSERT INTO `judaslanguages` VALUES (288,'PORTUGUES','entity','tarefa\n');
INSERT INTO `judaslanguages` VALUES (289,'PORTUGUES','priority','Prioridade\n');
INSERT INTO `judaslanguages` VALUES (290,'PORTUGUES','assignee','Responsável\n');
INSERT INTO `judaslanguages` VALUES (291,'PORTUGUES','duedate','Para dia\n');
INSERT INTO `judaslanguages` VALUES (292,'PORTUGUES','alarmdate','Data do Alarme\n');
INSERT INTO `judaslanguages` VALUES (293,'PORTUGUES','alarmdatev','Criar alarme para esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (294,'PORTUGUES','category','Categoria\n');
INSERT INTO `judaslanguages` VALUES (295,'PORTUGUES','status','Status\n');
INSERT INTO `judaslanguages` VALUES (296,'PORTUGUES','helpcontents','Tópicos de ajuda\n');
INSERT INTO `judaslanguages` VALUES (297,'PORTUGUES','tolimited','Devido a falta de privilégios você foi direcionado para uma tela limitada\n');
INSERT INTO `judaslanguages` VALUES (298,'PORTUGUES','briefover','Relatório sobre a tarefa\n');
INSERT INTO `judaslanguages` VALUES (299,'PORTUGUES','mightbebetter','Seria melhor você usar a opção de relatório\n');
INSERT INTO `judaslanguages` VALUES (300,'PORTUGUES','editthis','Edite esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (301,'PORTUGUES','alarmsettings','Opções do Alarme\n');
INSERT INTO `judaslanguages` VALUES (302,'PORTUGUES','closethisentity','Fechar esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (303,'PORTUGUES','deletethisentity','Deletar esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (304,'PORTUGUES','downloadpdf','Baixar relatório em PDF sobre esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (305,'PORTUGUES','downloadpdfs','Baixar relatório em PDF\n');
INSERT INTO `judaslanguages` VALUES (306,'PORTUGUES','close','Fechar\n');
INSERT INTO `judaslanguages` VALUES (307,'PORTUGUES','edit','Editar\n');
INSERT INTO `judaslanguages` VALUES (308,'PORTUGUES','delete','Deletar\n');
INSERT INTO `judaslanguages` VALUES (309,'PORTUGUES','pdfreport','Relatório em PDF\n');
INSERT INTO `judaslanguages` VALUES (310,'PORTUGUES','welcome1','Bem-vindo ao\n');
INSERT INTO `judaslanguages` VALUES (311,'PORTUGUES','intro1','Esta ferramenta é usada para grava as dúvidas dos clientes. Agora eles são\n');
INSERT INTO `judaslanguages` VALUES (312,'PORTUGUES','intro2','usuários registrados,<br>que no total são\n');
INSERT INTO `judaslanguages` VALUES (313,'PORTUGUES','intro3','tarefas logadas, para\n');
INSERT INTO `judaslanguages` VALUES (314,'PORTUGUES','intro4','clientes.\n');
INSERT INTO `judaslanguages` VALUES (315,'PORTUGUES','welcome','Bem-vindo\n');
INSERT INTO `judaslanguages` VALUES (316,'PORTUGUES','lastlogon','Última vez que logou\n');
INSERT INTO `judaslanguages` VALUES (317,'PORTUGUES','entitiestoday','tarefas para hoje\n');
INSERT INTO `judaslanguages` VALUES (318,'PORTUGUES','noentities','Não há nenhuma tarefa para hoje\n');
INSERT INTO `judaslanguages` VALUES (319,'PORTUGUES','gotomainpage','Ir para a página principal\n');
INSERT INTO `judaslanguages` VALUES (320,'PORTUGUES','main','Principal\n');
INSERT INTO `judaslanguages` VALUES (321,'PORTUGUES','addcusttodb','Adicionar o pedido do cliente na base de dados\n');
INSERT INTO `judaslanguages` VALUES (322,'PORTUGUES','add','Adicionar\n');
INSERT INTO `judaslanguages` VALUES (323,'PORTUGUES','viewbrief','Ver um relatório das tarefas gravadas na base de dados\n');
INSERT INTO `judaslanguages` VALUES (324,'PORTUGUES','entities','Tarefas\n');
INSERT INTO `judaslanguages` VALUES (325,'PORTUGUES','brieflistdel','Ver um relatório das tarefas apagadas da base de dados\n');
INSERT INTO `judaslanguages` VALUES (326,'PORTUGUES','delentities','Deletar tarefas\n');
INSERT INTO `judaslanguages` VALUES (327,'PORTUGUES','vacoa','Ver, adicionar ou mudar possíveis donos ou Responsávels\n');
INSERT INTO `judaslanguages` VALUES (328,'PORTUGUES','oa','Donos/Responsávels\n');
INSERT INTO `judaslanguages` VALUES (329,'PORTUGUES','vacc','Ver, adicionar ou modificar clientes\n');
INSERT INTO `judaslanguages` VALUES (330,'PORTUGUES','customers','Clientes\n');
INSERT INTO `judaslanguages` VALUES (331,'PORTUGUES','dumpi','Eliminar as vírgulas para exportar os dados da base de dados\n');
INSERT INTO `judaslanguages` VALUES (332,'PORTUGUES','phonebook1','Agenda de Telefones\n');
INSERT INTO `judaslanguages` VALUES (333,'PORTUGUES','phonebookshort','AT\n');
INSERT INTO `judaslanguages` VALUES (334,'PORTUGUES','sumverb','Ver e imprimir relatórios mais avançados\n');
INSERT INTO `judaslanguages` VALUES (335,'PORTUGUES','summary','Relatório\n');
INSERT INTO `judaslanguages` VALUES (336,'PORTUGUES','logout','Sair\n');
INSERT INTO `judaslanguages` VALUES (337,'PORTUGUES','maninfo','Informações de Administração\n');
INSERT INTO `judaslanguages` VALUES (338,'PORTUGUES','maninfoverb','Relatórios de estatísticas para Administração\n');
INSERT INTO `judaslanguages` VALUES (339,'PORTUGUES','sitestats','Estatísticas do site\n');
INSERT INTO `judaslanguages` VALUES (340,'PORTUGUES','sitestatsverb','As estatísticas deste site\n');
INSERT INTO `judaslanguages` VALUES (341,'PORTUGUES','administration','Administração\n');
INSERT INTO `judaslanguages` VALUES (342,'PORTUGUES','administrationverb','Funçoes de Administração\n');
INSERT INTO `judaslanguages` VALUES (343,'PORTUGUES','helpcontentsverb','Mostrar lista de conteúdo da ajuda\n');
INSERT INTO `judaslanguages` VALUES (344,'PORTUGUES','dateinvalid','A data que você escolhe é inválida.n A data não foi escolhida.\n');
INSERT INTO `judaslanguages` VALUES (345,'PORTUGUES','entrysaved','Digitar número do pedido\n');
INSERT INTO `judaslanguages` VALUES (346,'PORTUGUES','wasadded','foi adicionado.\n');
INSERT INTO `judaslanguages` VALUES (347,'PORTUGUES','deleting1','Deletando\n');
INSERT INTO `judaslanguages` VALUES (348,'PORTUGUES','deleting2','arquivo(s). Aperte o botão abaixo para confirmar.\n');
INSERT INTO `judaslanguages` VALUES (349,'PORTUGUES','confdel','Confirme deletagem\n');
INSERT INTO `judaslanguages` VALUES (350,'PORTUGUES','deletingentity','Deletando tarefa\n');
INSERT INTO `judaslanguages` VALUES (351,'PORTUGUES','ownedby','pertence à\n');
INSERT INTO `judaslanguages` VALUES (352,'PORTUGUES','assignedto','Responsável para\n');
INSERT INTO `judaslanguages` VALUES (353,'PORTUGUES','curstat','Status atual\n');
INSERT INTO `judaslanguages` VALUES (354,'PORTUGUES','created','criado\n');
INSERT INTO `judaslanguages` VALUES (355,'PORTUGUES','lastupdate','última atualização\n');
INSERT INTO `judaslanguages` VALUES (356,'PORTUGUES','deleteerror','Você não pode deletar esta tarefa pois ela não foi terminada\n');
INSERT INTO `judaslanguages` VALUES (357,'PORTUGUES','confirmdel','Clique aqui para deletar esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (358,'PORTUGUES','search','Procura\n');
INSERT INTO `judaslanguages` VALUES (359,'PORTUGUES','thereare','São\n');
INSERT INTO `judaslanguages` VALUES (360,'PORTUGUES','openentities','Abrir tarefas\n');
INSERT INTO `judaslanguages` VALUES (361,'PORTUGUES','noopen','Não há tarefas abertas.\n');
INSERT INTO `judaslanguages` VALUES (362,'PORTUGUES','nonexistent','Você digitou um número de tarefa que não existe!\n');
INSERT INTO `judaslanguages` VALUES (363,'PORTUGUES','editing','Editando\n');
INSERT INTO `judaslanguages` VALUES (364,'PORTUGUES','wasclosed','Esta tarefa foi fechada\n');
INSERT INTO `judaslanguages` VALUES (365,'PORTUGUES','newentity','Nova tarefa\n');
INSERT INTO `judaslanguages` VALUES (366,'PORTUGUES','isdeleted','Esta é uma tarefa deletada\n');
INSERT INTO `judaslanguages` VALUES (367,'PORTUGUES','iswaiting','Aguardando outra pessoa\n');
INSERT INTO `judaslanguages` VALUES (368,'PORTUGUES','doesntbelonghere','Esta tarefa não pertence a este local\n');
INSERT INTO `judaslanguages` VALUES (369,'PORTUGUES','listofatt','Listar arquivos anexados a esta tarefa\n');
INSERT INTO `judaslanguages` VALUES (370,'PORTUGUES','filename','Nome do arquivo\n');
INSERT INTO `judaslanguages` VALUES (371,'PORTUGUES','filesize','Tamanho\n');
INSERT INTO `judaslanguages` VALUES (372,'PORTUGUES','creationdate','Data de criação\n');
INSERT INTO `judaslanguages` VALUES (373,'PORTUGUES','deletefile','Deletar\n');
INSERT INTO `judaslanguages` VALUES (374,'PORTUGUES','attachfile','Anexar arquivo\n');
INSERT INTO `judaslanguages` VALUES (375,'PORTUGUES','saveclose','Salvar e Fechar\n');
INSERT INTO `judaslanguages` VALUES (376,'PORTUGUES','cancel','Cancelar\n');
INSERT INTO `judaslanguages` VALUES (377,'PORTUGUES','save','Salvar para base de dados\n');
INSERT INTO `judaslanguages` VALUES (378,'PORTUGUES','noaction','Erro, nenhuma ação escolhida\n');
INSERT INTO `judaslanguages` VALUES (379,'PORTUGUES','zailo','falta zero consignados\n');
INSERT INTO `judaslanguages` VALUES (380,'PORTUGUES','name','Nome\n');
INSERT INTO `judaslanguages` VALUES (381,'PORTUGUES','usrwarning','Se uma caixa está desabilitada (cinza), significa que seu dono ou responsável possui uma conta limitada, e portanto o nome não pode ser mudado<br>ou os dados podem ser perdidos.\n');
INSERT INTO `judaslanguages` VALUES (382,'PORTUGUES','ownassindb','Donos os responsáveis na base de dados\n');
INSERT INTO `judaslanguages` VALUES (383,'PORTUGUES','addownass','Adicionar dono/responsável\n');
INSERT INTO `judaslanguages` VALUES (384,'PORTUGUES','apply','Aplicar alterações\n');
INSERT INTO `judaslanguages` VALUES (385,'PORTUGUES','custindb','Clientes na base de dados\n');
INSERT INTO `judaslanguages` VALUES (386,'PORTUGUES','addcust','Adicionar um cliente\n');
INSERT INTO `judaslanguages` VALUES (387,'PORTUGUES','selectfields','Por favor selecionar os campos que deseja exportar\n');
INSERT INTO `judaslanguages` VALUES (388,'PORTUGUES','lastupdatedate','Data da última atualização\n');
INSERT INTO `judaslanguages` VALUES (389,'PORTUGUES','lastupdatetime','Hora da última atualização\n');
INSERT INTO `judaslanguages` VALUES (390,'PORTUGUES','closedate','Data de fechamento\n');
INSERT INTO `judaslanguages` VALUES (391,'PORTUGUES','waitingcsv','Aguardando\n');
INSERT INTO `judaslanguages` VALUES (392,'PORTUGUES','doesntcsv','Não pertence a este local\n');
INSERT INTO `judaslanguages` VALUES (393,'PORTUGUES','contents','Conteúdo\n');
INSERT INTO `judaslanguages` VALUES (394,'PORTUGUES','alreadyselected','<b>Sua requisição foi gravada</b>\n');
INSERT INTO `judaslanguages` VALUES (395,'PORTUGUES','sep','Separação com caracteres\n');
INSERT INTO `judaslanguages` VALUES (396,'PORTUGUES','scqp','Separado por ponto-vírgula (;) (recomendado)\n');
INSERT INTO `judaslanguages` VALUES (397,'PORTUGUES','cqp','Separado com dois pontos (:)\n');
INSERT INTO `judaslanguages` VALUES (398,'PORTUGUES','kqp','Separado com vírgula (,)\n');
INSERT INTO `judaslanguages` VALUES (399,'PORTUGUES','csvwarning','Quando a caixa de download aparecer, seleciona \\\'Abrir o arquivo no local atual\\\'.<br> Talvez a mesma janela reapareça, se aparecer clique em \\\"Abrir\\\" novamente. Isto deve abrir seu Excel <br>com os dados exportados.\n');
INSERT INTO `judaslanguages` VALUES (400,'PORTUGUES','downloadexport','Baixar arquivo exportado\n');
INSERT INTO `judaslanguages` VALUES (401,'PORTUGUES','repdownloaded','Relotório foi baixado\n');
INSERT INTO `judaslanguages` VALUES (402,'PORTUGUES','endofreport','Fim do relatório. Tenha um ótimo dia :)\n');
INSERT INTO `judaslanguages` VALUES (403,'PORTUGUES','noresults','Seu pedido não obteve nenhum resultado.\n');
INSERT INTO `judaslanguages` VALUES (404,'PORTUGUES','entitiesfound','tarefas encontradas.\n');
INSERT INTO `judaslanguages` VALUES (405,'PORTUGUES','pbexport','exportar agenda de telefones\n');
INSERT INTO `judaslanguages` VALUES (406,'PORTUGUES','endofpbexport','<red> -- Fim do Relatório --\n');
INSERT INTO `judaslanguages` VALUES (407,'PORTUGUES','pbexpmade','Arquivo de exportação da agenda de telefones criado\n');
INSERT INTO `judaslanguages` VALUES (408,'PORTUGUES','wasdeleted','foi deletado\n');
INSERT INTO `judaslanguages` VALUES (409,'PORTUGUES','pbdelconf','a que deseja apagar esta gravação?\n');
INSERT INTO `judaslanguages` VALUES (410,'PORTUGUES','fname','Primeiro nome\n');
INSERT INTO `judaslanguages` VALUES (411,'PORTUGUES','lname','Sobrenome\n');
INSERT INTO `judaslanguages` VALUES (412,'PORTUGUES','tel','Telefone\n');
INSERT INTO `judaslanguages` VALUES (413,'PORTUGUES','company','Empresa\n');
INSERT INTO `judaslanguages` VALUES (414,'PORTUGUES','dep','Departamento\n');
INSERT INTO `judaslanguages` VALUES (415,'PORTUGUES','title','Título\n');
INSERT INTO `judaslanguages` VALUES (416,'PORTUGUES','room','Quarto\n');
INSERT INTO `judaslanguages` VALUES (417,'PORTUGUES','deletepb','Deletar\n');
INSERT INTO `judaslanguages` VALUES (418,'PORTUGUES','pbrecadded','Seu contato foi adicionado na agenda de telefones.\n');
INSERT INTO `judaslanguages` VALUES (419,'PORTUGUES','pbapp','Suas alterações foram aplicadas.\n');
INSERT INTO `judaslanguages` VALUES (420,'PORTUGUES','pbwarning','Por favor preencha pelo menos o sobrenome!\n');
INSERT INTO `judaslanguages` VALUES (421,'PORTUGUES','addtopb','Adicionar a agenda de telefones\n');
INSERT INTO `judaslanguages` VALUES (422,'PORTUGUES','pbresults','Resultados para sua pesquisa\n');
INSERT INTO `judaslanguages` VALUES (423,'PORTUGUES','options','Opções\n');
INSERT INTO `judaslanguages` VALUES (424,'PORTUGUES','resfound','resultados encontrados\n');
INSERT INTO `judaslanguages` VALUES (425,'PORTUGUES','pbcont1','Esta agenda de telefones contém\n');
INSERT INTO `judaslanguages` VALUES (426,'PORTUGUES','pbcont2','contatos\n');
INSERT INTO `judaslanguages` VALUES (427,'PORTUGUES','pbaddrec','adicionar contato\n');
INSERT INTO `judaslanguages` VALUES (428,'PORTUGUES','entsum','Relatório de tarefas\n');
INSERT INTO `judaslanguages` VALUES (429,'PORTUGUES','showonly','Mostra apenas\n');
INSERT INTO `judaslanguages` VALUES (430,'PORTUGUES','all','Tudo\n');
INSERT INTO `judaslanguages` VALUES (431,'PORTUGUES','inccont','Adicionar comentários a tarefa\n');
INSERT INTO `judaslanguages` VALUES (432,'PORTUGUES','incldel','Incluir tarefas excluidas\n');
INSERT INTO `judaslanguages` VALUES (433,'PORTUGUES','dlacsv','Baixar resultado como CSV\n');
INSERT INTO `judaslanguages` VALUES (434,'PORTUGUES','briefo','Dados resumidos\n');
INSERT INTO `judaslanguages` VALUES (435,'PORTUGUES','mustcontain','Tarefa deve conter texto\n');
INSERT INTO `judaslanguages` VALUES (436,'PORTUGUES','please','Por favor faça sua escolha...\n');
INSERT INTO `judaslanguages` VALUES (437,'PORTUGUES','remarks','Remarcar\n');
INSERT INTO `judaslanguages` VALUES (438,'PORTUGUES','hasfilessum','Esta tarefa possui arquivos anexados\n');
INSERT INTO `judaslanguages` VALUES (439,'PORTUGUES','expired','A data de realização desta tarefa expirou!\n');
INSERT INTO `judaslanguages` VALUES (440,'PORTUGUES','thisiswaiting','Esta tarefa está aguardando ação de outra pessoa.\n');
INSERT INTO `judaslanguages` VALUES (441,'PORTUGUES','thisdoesntbelong','Este tarefa realmente não pertence a este local\n');
INSERT INTO `judaslanguages` VALUES (442,'PORTUGUES','clear','limpar\n');
INSERT INTO `judaslanguages` VALUES (443,'PORTUGUES','wrongpwd','Senha incorreta. Por favor tente novamente ou se mande\n');
INSERT INTO `judaslanguages` VALUES (444,'PORTUGUES','havetoenterpwd','Visto que sua conta não possui privilégios de administrador, você terá que colocar a senha de administrador\n');
INSERT INTO `judaslanguages` VALUES (445,'PORTUGUES','adm','Administração\n');
INSERT INTO `judaslanguages` VALUES (446,'PORTUGUES','nopwd','Visto que sua conta tem privilégios de administrador, a senha para o mesmo não foi pedida.\n');
INSERT INTO `judaslanguages` VALUES (447,'PORTUGUES','imported','print \\\"Foram $imported gravaçoes importadas.\\\";\n');
INSERT INTO `judaslanguages` VALUES (448,'PORTUGUES','ignored','gravaçoes foram ignoradas por conter um campo vazio.\n');
INSERT INTO `judaslanguages` VALUES (449,'PORTUGUES','impwarning','Para impedir que uma gravação seja importada, esvazie o campo \\\"Nome\\\". Corrija os que estiverem errados.\n');
INSERT INTO `judaslanguages` VALUES (450,'PORTUGUES','commawarning','Visto que você escolheu importar um arquivo separado por vírgulas, fique atento com combinações do tipo sobrenome, nome (que são comuns no Outlook) que podem produzir efeitos indesejados.\n');
INSERT INTO `judaslanguages` VALUES (451,'PORTUGUES','importinpb','Importar dados da agenda de telefones\n');
INSERT INTO `judaslanguages` VALUES (452,'PORTUGUES','pbimpwarning','As informações CSV que você colou <i>devem</i> conter todos campos, contudo eles podem ser vazios:\n');
INSERT INTO `judaslanguages` VALUES (453,'PORTUGUES','paste','Cole seu texto aqui ...\n');
INSERT INTO `judaslanguages` VALUES (454,'PORTUGUES','pleasechoose','Por favor selecione uma das opções abaixo:\n');
INSERT INTO `judaslanguages` VALUES (455,'PORTUGUES','chgsys','Trocar valores do sistema\n');
INSERT INTO `judaslanguages` VALUES (456,'PORTUGUES','impphone','Importar dadso da agenda de telefones\n');
INSERT INTO `judaslanguages` VALUES (457,'PORTUGUES','viewfiles','Ver arquivos na base de dados\n');
INSERT INTO `judaslanguages` VALUES (458,'PORTUGUES','delallclosed','Deletar todas as tarefas concluídas\n');
INSERT INTO `judaslanguages` VALUES (459,'PORTUGUES','eahelp','Adicionar/Editar tópicos de ajuda\n');
INSERT INTO `judaslanguages` VALUES (460,'PORTUGUES','physdel','Deletar fisicamente uma tarefa deletada\n');
INSERT INTO `judaslanguages` VALUES (461,'PORTUGUES','viewlog','Ver logs e estatísticas\n');
INSERT INTO `judaslanguages` VALUES (462,'PORTUGUES','manacc','Administrar contas\n');
INSERT INTO `judaslanguages` VALUES (463,'PORTUGUES','isdel','foi deletado\n');
INSERT INTO `judaslanguages` VALUES (464,'PORTUGUES','delfile','Deletando arquivo fisicamente\n');
INSERT INTO `judaslanguages` VALUES (465,'PORTUGUES','physdelwarning','Por favor digite o ID da tarefa<b>fechada e deletada</b> que você quer <b>fisicamente</b> deletar:\n');
INSERT INTO `judaslanguages` VALUES (466,'PORTUGUES','confphysdel','Clique no botão abaixo para confirmar deletação física.\n');
INSERT INTO `judaslanguages` VALUES (467,'PORTUGUES','addhelp','Adicionar opção de ajuda:\n');
INSERT INTO `judaslanguages` VALUES (468,'PORTUGUES','editaccount','Editar uma conta\n');
INSERT INTO `judaslanguages` VALUES (469,'PORTUGUES','addaccount','Adicionar uma conta\n');
INSERT INTO `judaslanguages` VALUES (470,'PORTUGUES','password','Senha\n');
INSERT INTO `judaslanguages` VALUES (471,'PORTUGUES','addu','Adicionar Usuário\n');
INSERT INTO `judaslanguages` VALUES (472,'PORTUGUES','btmap','Voltar para a página principal do Administrador\n');
INSERT INTO `judaslanguages` VALUES (473,'PORTUGUES','passwarn','deixe os dois campos em branco para manter a senha atual\n');
INSERT INTO `judaslanguages` VALUES (474,'PORTUGUES','limited','Limitado\n');
INSERT INTO `judaslanguages` VALUES (475,'PORTUGUES','normal','Normal\n');
INSERT INTO `judaslanguages` VALUES (476,'PORTUGUES','adminrights','Administrador\n');
INSERT INTO `judaslanguages` VALUES (477,'PORTUGUES','yes','Sim\n');
INSERT INTO `judaslanguages` VALUES (478,'PORTUGUES','no','Não\n');
INSERT INTO `judaslanguages` VALUES (479,'PORTUGUES','ela','Editando conta de login\n');
INSERT INTO `judaslanguages` VALUES (480,'PORTUGUES','dta','Deletar esta conta\n');
INSERT INTO `judaslanguages` VALUES (481,'PORTUGUES','passmatcherror','Senha não confere. Pressione \\\'voltar\\\' no seu navegador e tente novamente.\n');
INSERT INTO `judaslanguages` VALUES (482,'PORTUGUES','nimut','Ocorreu um erro!<br><br>Esta conta existe, mas ela<br>não se refere a nenhum usuário na base de dados para o qual possam ser designadas tarefas.<br><br>Verifique o nome tente novamente.\n');
INSERT INTO `judaslanguages` VALUES (483,'PORTUGUES','uwchala','Usuários que podem ter conta limitada\n');
INSERT INTO `judaslanguages` VALUES (484,'PORTUGUES','tawu','A conta foi atualizada\n');
INSERT INTO `judaslanguages` VALUES (485,'PORTUGUES','setting','Configurações\n');
INSERT INTO `judaslanguages` VALUES (486,'PORTUGUES','value','Valores\n');
INSERT INTO `judaslanguages` VALUES (487,'PORTUGUES','discription','Descrição\n');
INSERT INTO `judaslanguages` VALUES (488,'PORTUGUES','ocsvifb','Ou troque os valores do sistema no formulário abaixo\n');
INSERT INTO `judaslanguages` VALUES (489,'PORTUGUES','csvnow','Troque os valores do sistema\n');
INSERT INTO `judaslanguages` VALUES (490,'PORTUGUES','plzenterpwd','Por favor digite a senha\n');
INSERT INTO `judaslanguages` VALUES (491,'PORTUGUES','eor','Fim do relatório\n');
INSERT INTO `judaslanguages` VALUES (492,'PORTUGUES','smtsm','Selecione mais para ver mais...\n');
INSERT INTO `judaslanguages` VALUES (493,'PORTUGUES','dlmspdf','ou clique aqui para baixar (mais compacto) um relatório em PDF\n');
INSERT INTO `judaslanguages` VALUES (494,'PORTUGUES','sts','Resumos a mostrar\n');
INSERT INTO `judaslanguages` VALUES (495,'PORTUGUES','oqs','Relatório Geral Resumido\n');
INSERT INTO `judaslanguages` VALUES (496,'PORTUGUES','eobu','Tarefas possuidas por usuários\n');
INSERT INTO `judaslanguages` VALUES (497,'PORTUGUES','eatu','Tarefas com usuários responsáveis\n');
INSERT INTO `judaslanguages` VALUES (498,'PORTUGUES','sae','Tarefas designadas para o mesmo usuário\n');
INSERT INTO `judaslanguages` VALUES (499,'PORTUGUES','etdbh','Tarefas que não pertencem a este local\n');
INSERT INTO `judaslanguages` VALUES (500,'PORTUGUES','ewfsea','Tarefas aguardando ação de outra pessoa\n');
INSERT INTO `judaslanguages` VALUES (501,'PORTUGUES','epc','Tarefas por Cliente\n');
INSERT INTO `judaslanguages` VALUES (502,'PORTUGUES','oepa','Tarefas expiradas, por usuário\n');
INSERT INTO `judaslanguages` VALUES (503,'PORTUGUES','deleted','Deletado\n');
INSERT INTO `judaslanguages` VALUES (504,'PORTUGUES','total','Total\n');
INSERT INTO `judaslanguages` VALUES (505,'PORTUGUES','ofwhich','das quais\n');
INSERT INTO `judaslanguages` VALUES (506,'PORTUGUES','allround','Todos valores sõa aproximados\n');
INSERT INTO `judaslanguages` VALUES (507,'PORTUGUES','atac','ou muito aproximados\n');
INSERT INTO `judaslanguages` VALUES (508,'PORTUGUES','edd','Datas de expiração\n');
INSERT INTO `judaslanguages` VALUES (509,'PORTUGUES','dontbelonghere','Tarefas que não pertencem a este local\n');
INSERT INTO `judaslanguages` VALUES (510,'PORTUGUES','eatw','Tarefas adicionadas esta semana\n');
INSERT INTO `judaslanguages` VALUES (511,'PORTUGUES','ectw','Tarefas concluídas esta semana\n');
INSERT INTO `judaslanguages` VALUES (512,'PORTUGUES','eatm','Tarefas adicionadas neste mês\n');
INSERT INTO `judaslanguages` VALUES (513,'PORTUGUES','ectm','Tarefas concluídas neste mês\n');
INSERT INTO `judaslanguages` VALUES (514,'PORTUGUES','of','De\n');
INSERT INTO `judaslanguages` VALUES (515,'PORTUGUES','tad','tarefas contadas, uma média total \\\'de realização\\\' desde a adição de uma tarefa até seu fechamento\n');
INSERT INTO `judaslanguages` VALUES (516,'PORTUGUES','cuaeoay','Contados usando <u>todas</u> tarefas concluídas da base de dados, ao longo de <u>todos</u> os anos\n');
INSERT INTO `judaslanguages` VALUES (517,'PORTUGUES','users','Usuários\n');
INSERT INTO `judaslanguages` VALUES (518,'PORTUGUES','customers','Clientes\n');
INSERT INTO `judaslanguages` VALUES (519,'PORTUGUES','zoilo','zero donos estão faltando\n');
INSERT INTO `judaslanguages` VALUES (520,'PORTUGUES','ombla','Ou : ou talvez tarefas que não tem responsáveis ou não foram designadas(...)\n');
INSERT INTO `judaslanguages` VALUES (521,'PORTUGUES','andassignee','e designadas\n');
INSERT INTO `judaslanguages` VALUES (522,'PORTUGUES','selfassig','Auto-Designadas\n');
INSERT INTO `judaslanguages` VALUES (523,'PORTUGUES','aohnsae','Outros donos não possuem tarefas auto-designadas.\n');
INSERT INTO `judaslanguages` VALUES (524,'PORTUGUES','onavarage','Em média\n');
INSERT INTO `judaslanguages` VALUES (525,'PORTUGUES','oaoedbh','de todas tarefas <b>abertas</b> não pertencem a este local\n');
INSERT INTO `judaslanguages` VALUES (526,'PORTUGUES','teaair','A tarefa e todas as sua anotações foram fisicamente deletadas\n');
INSERT INTO `judaslanguages` VALUES (527,'PORTUGUES','cookiewarning','Não use esta função em computadores públicos!\n');
INSERT INTO `judaslanguages` VALUES (528,'PORTUGUES','username','Usuário\n');
INSERT INTO `judaslanguages` VALUES (529,'PORTUGUES','saveusername','Lembrar usuário\n');
INSERT INTO `judaslanguages` VALUES (530,'PORTUGUES','clearusername','Esquecer usuário\n');
INSERT INTO `judaslanguages` VALUES (531,'PORTUGUES','savepassword','Lmebrar senha\n');
INSERT INTO `judaslanguages` VALUES (532,'PORTUGUES','clearpassword','Esquecer senha\n');
INSERT INTO `judaslanguages` VALUES (533,'PORTUGUES','signedoff','Você foi deslogado. Por favor digite seu usuário e senha para entrar novamente\n');
INSERT INTO `judaslanguages` VALUES (534,'PORTUGUES','signedoffdue1','Você foi deslogado devido a\n');
INSERT INTO `judaslanguages` VALUES (535,'PORTUGUES','signedoffdue2','minutos de inatividade\n');
INSERT INTO `judaslanguages` VALUES (536,'PORTUGUES','sysmsg','O Administrador do sistema deixou uma mensagem para você\n');
INSERT INTO `judaslanguages` VALUES (537,'PORTUGUES','pleaseenter','Por favor digite seu usuário e senha\n');
INSERT INTO `judaslanguages` VALUES (538,'PORTUGUES','language','Língua\n');
INSERT INTO `judaslanguages` VALUES (539,'PORTUGUES','pushpdf','Baixar resultados em arquivo PDF\n');
INSERT INTO `judaslanguages` VALUES (540,'PORTUGUES','managementheader','Bem-vindo a interface de usuário limitado. você está no sistema como\n');
INSERT INTO `judaslanguages` VALUES (541,'PORTUGUES','oefm','Tarefas abertas para\n');
INSERT INTO `judaslanguages` VALUES (542,'PORTUGUES','showresults','Método do Relatório\n');
INSERT INTO `judaslanguages` VALUES (543,'PORTUGUES','verbose','Verbose\n');
INSERT INTO `judaslanguages` VALUES (544,'PORTUGUES','verbosewithcontents','Verbose com tópicos\n');
INSERT INTO `judaslanguages` VALUES (545,'PORTUGUES','briefsum','Resumo rápido\n');
INSERT INTO `judaslanguages` VALUES (546,'PORTUGUES','downloadsumpdf','Baixar resumo como arquivo PDF\n');
INSERT INTO `judaslanguages` VALUES (547,'PORTUGUES','downloadsumcsv','Baixar resumo em arquivo Excel\n');
INSERT INTO `judaslanguages` VALUES (548,'PORTUGUES','packman','Administrar pacotes de linguagem\n');
INSERT INTO `judaslanguages` VALUES (549,'PORTUGUES','openinnewwindow','Abrir em uma nova janela\n');
INSERT INTO `judaslanguages` VALUES (550,'PORTUGUES','delcust','Deletar este usuário (<b>nenhuma</b> confirmação será pedida)\n');
INSERT INTO `judaslanguages` VALUES (551,'PORTUGUES','nousers1','Não há donos / responsáveis configurados. Antes de começar a usar o CRM, você precisa adicionar pelo menos um. Clique em \\\'Donos/Responsáveis\\\' para adicionar possíveis donos ou responsáveis!\n');
INSERT INTO `judaslanguages` VALUES (552,'PORTUGUES','custhomepage','Homepage\n');
INSERT INTO `judaslanguages` VALUES (553,'PORTUGUES','custremarks','Remarcação\n');
INSERT INTO `judaslanguages` VALUES (554,'PORTUGUES','customeraddress','Endereço do cliente\n');
INSERT INTO `judaslanguages` VALUES (555,'PORTUGUES','contactemail','E-mail para contato\n');
INSERT INTO `judaslanguages` VALUES (556,'PORTUGUES','contactphone','Telefone para contato\n');
INSERT INTO `judaslanguages` VALUES (557,'PORTUGUES','contact','Contato\n');
INSERT INTO `judaslanguages` VALUES (558,'PORTUGUES','contacttitle','Título de contato (ex. Sr.)\n');
INSERT INTO `judaslanguages` VALUES (559,'PORTUGUES','custdelexplain','Este cliente não pode ser deletado pois tem tarefas que pertencem a eles\n');
INSERT INTO `judaslanguages` VALUES (560,'PORTUGUES','editextras','Editar valores extras\n');
INSERT INTO `judaslanguages` VALUES (561,'PORTUGUES','fieldname','Nome\n');
INSERT INTO `judaslanguages` VALUES (562,'PORTUGUES','iftynmvhpcysa','Se você acha que precisa de mais nomes aqui, por favor contate o administrador do seu CRM.\n');
INSERT INTO `judaslanguages` VALUES (563,'PORTUGUES','extrafields','Campos extras\n');
INSERT INTO `judaslanguages` VALUES (564,'PORTUGUES','uinw','Atualizar em nova janela\n');
INSERT INTO `judaslanguages` VALUES (565,'PORTUGUES','nocustomers1','Não há clientes configurados. Antes de usar o CRM, você precisa fazer isto. Clique no menu \\\'Clientes\\\' para adicionar pelo menos um cliente!\n');
INSERT INTO `judaslanguages` VALUES (566,'PORTUGUES','nousersandnocustomers1','Não há clientes nem possíveis Donos/Designados configurados. Antes que você possa usar o CRM, você precisa fazer isto. Clique no menu \\\'Clientes\\\' para adicionar pelo menos um cliente, e depois no menu \\\'Donos/Designados\\\' para adicionar pelo menos um pos');
INSERT INTO `judaslanguages` VALUES (567,'PORTUGUES','managerepositories','Administrar repositores\n');
INSERT INTO `judaslanguages` VALUES (568,'ENGLISH','stillchecked1','This file is still locked for editing by');
INSERT INTO `judaslanguages` VALUES (569,'ENGLISH','stillchecked2','. Please stop editing this file before trying to check it in.');
INSERT INTO `judaslanguages` VALUES (570,'ENGLISH','saveasnewentity','Save as new entity');
INSERT INTO `judaslanguages` VALUES (573,'GLOBAL','current-language','PORTUGUES');
INSERT INTO `judaslanguages` VALUES (574,'GLOBAL','current-language-mask','PORTUGUES');

