#
# Table structure for table judasloginusers
#

CREATE TABLE `judasloginusers` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(50) NOT NULL default '',
  `password` varchar(50) default NULL,
  `PROFILE` varchar(10) NOT NULL default '',
  `type` enum('normal','limited') NOT NULL default 'normal',
  `active` enum('yes','no') NOT NULL default 'yes',
  `exptime` varchar(40) NOT NULL default '',
  `noexp` enum('n','y') NOT NULL default 'n',
  `FULLNAME` varchar(150) NOT NULL default '',
  `EMAIL` varchar(150) NOT NULL default '',
  `CLLEVEL` varchar(50) NOT NULL default 'ro',
  `administrator` enum('yes','no') NOT NULL default 'no',
  `LASTFILTER` longtext NOT NULL,
  `LASTSORT` varchar(50) NOT NULL default '',
  `RECEIVEDAILYMAIL` enum('No','Yes') NOT NULL default 'No',
  `RECEIVEALLOWNERUPDATES` enum('n','y') NOT NULL default 'n',
  `RECEIVEALLASSIGNEEUPDATES` enum('n','y') NOT NULL default 'n',
  `HIDEADDTAB` char(1) NOT NULL default '',
  `HIDECSVTAB` char(1) NOT NULL default '',
  `HIDESUMMARYTAB` char(1) NOT NULL default '',
  `HIDEENTITYTAB` char(1) NOT NULL default '',
  `HIDEPBTAB` char(1) NOT NULL default '',
  `SHOWDELETEDVIEWOPTION` char(1) NOT NULL default '',
  `HIDECUSTOMERTAB` char(1) NOT NULL default '',
  `SAVEDSEARCHES` longtext NOT NULL,
  `EMAILCREDENTIALS` longtext NOT NULL,
  `ENTITYADDFORM` varchar(10) NOT NULL default '',
  `ENTITYEDITFORM` varchar(10) NOT NULL default '',
  `LIMITTOCUSTOMERS` longtext NOT NULL,
  `ADDFORMS` longtext NOT NULL,
  `ELISTLAYOUT` text NOT NULL,
  `CLISTLAYOUT` text NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `name` (`name`),
  FULLTEXT KEY `SAVEDSEARCHES` (`SAVEDSEARCHES`),
  FULLTEXT KEY `EMAILCREDENTIALS` (`EMAILCREDENTIALS`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='CRM User definition table';

#
# Dumping data for table judasloginusers
#

INSERT INTO `judasloginusers` VALUES (1,'deleted_user_1153770566_Maninho','565491d704013245','','','no','PORTUGUES','n','Administrator Maninho','ti@grupovanguarda.com','rw','yes','a:6:{s:16:\"pdfiltercustomer\";s:3:\"all\";s:14:\"pdfilterstatus\";s:3:\"all\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:1:\"1\";s:16:\"pdfilterassignee\";s:1:\"1\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','category-----DESC','Yes','n','n','','','','','','','','','','','','','N;','','a:5:{s:2:\"id\";b:1;s:11:\"cb_custname\";b:1;s:10:\"cb_contact\";b:1;s:16:\"cb_contact_phone\";b:1;s:9:\"cb_active\";b:1;}');
INSERT INTO `judasloginusers` VALUES (2,'deleted_user_1149271037_Mandry','565491d704013245','','','no','PORTUGUES','n','Grupo Vanguarda','mandry2@casadaweb.net','read-only-all','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (3,'Grupo Vanguarda','565491d704013245','','','no','','n','','mandry2@casadaweb.net','ro+','','','','','n','n','n','n','','n','','','n','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (4,'deleted_user_1149292675_Joao','565491d704013245','','','no','','n','Grupo Vanguarda','mandry2@casadaweb.net','ro','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (5,'deleted_user_1149301205_Jean','565491d704013245','','','no','','n','Jean Augusto','malao.nostraghamus@bol.com.br','full-access-see-own-assigned-and-owned-entities','','a:6:{s:16:\"pdfiltercustomer\";s:1:\"1\";s:14:\"pdfilterstatus\";N;s:16:\"pdfilterpriority\";N;s:13:\"pdfilterowner\";N;s:16:\"pdfilterassignee\";N;s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','No','n','n','1','1','1','1','1','1','1','','','','','','a:2:{i:0;s:7:\"default\";i:1;s:1:\"7\";}','','');
INSERT INTO `judasloginusers` VALUES (6,'deleted_user_1149301209_Jorge','565491d704013245','','','no','','n','Jorga da gavia','mandry2@casadaweb.net','full-access-see-own-assigned-and-owned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (7,'deleted_user_1149301775_Lagarto','565491d704013245','Default','normal','no','','n','ajuiahauih','marciobuzatto@hotmail.com','rw','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (8,'deleted_user_1153770451_Marcelo','565491d704013245','','','no','','n','Marcelo Nova','malao.nostraghamus@bol.com.br','full-access-own-entities','','a:6:{s:16:\"pdfiltercustomer\";s:3:\"all\";s:14:\"pdfilterstatus\";s:16:\"Tarefa Concluida\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:3:\"all\";s:16:\"pdfilterassignee\";s:3:\"all\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (9,'Jardel','565491d704013245','','','yes','','n','Jardel de souza','mandry2@casadaweb.net','full-access-own-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (10,'Mandry','565491d704013245','','','yes','','n','Mauricio Pacheco','mandry@casadaweb.net','rw','yes','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (11,'Isrel','773359240eb9a1d9','','','yes','','n','Isrel Ramos','ti@grupovanguarda.com','rw','yes','a:6:{s:16:\"pdfiltercustomer\";s:3:\"all\";s:14:\"pdfilterstatus\";s:3:\"all\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:3:\"all\";s:16:\"pdfilterassignee\";s:3:\"all\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','Yes','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (12,'Reges','565491d704013245','','','yes','','n','Reges Centenauro','reges@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (13,'adilson','565491d704013245','','','yes','','n','Adilson Santiago','adilson@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (14,'adilsonkanarek','565491d704013245','','','yes','','n','Adilson Kanarek','adilsonkanarek@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (15,'adriane','565491d704013245','Default','normal','yes','','n','Adriane - Rc','adriane@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (16,'aloyzio','565491d704013245','Default','normal','yes','','n','Aloyzio - Ideal Porc','aloyzio@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (17,'amancio','565491d704013245','Default','normal','yes','','n','José Amancio','amancio@grupovanguarda.com','full-access-see-own-assigned-entities','','a:6:{s:16:\"pdfiltercustomer\";s:1:\"1\";s:14:\"pdfilterstatus\";N;s:16:\"pdfilterpriority\";N;s:13:\"pdfilterowner\";N;s:16:\"pdfilterassignee\";N;s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (18,'anderson','565491d704013245','','','yes','','n','Anderson - Engenheiro Ambiental','','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (19,'andre','565491d704013245','Default','normal','yes','','n','André Garcia','andre@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (20,'carlosalexandre','565491d704013245','Default','normal','yes','','n','Carlos Alexandre - Ideal Porc','carlosalexandre@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (21,'carlosmardoque','565491d704013245','Default','normal','yes','','n','Carlos Mardoque - Rc','carlosmardoque@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (22,'cassius','565491d704013245','Default','normal','yes','','n','Cassius Zancanella','cassius@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (23,'claudio','565491d704013245','Default','normal','yes','','n','Claudio Escobar','claudio@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (24,'cleiton','565491d704013245','Default','normal','yes','','n','Cleiton - Mãe Margarida','cleiton@grupovanguarda.com','full-access-see-own-assigned-entities','','a:6:{s:16:\"pdfiltercustomer\";s:1:\"2\";s:14:\"pdfilterstatus\";s:6:\"Aberto\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:2:\"36\";s:16:\"pdfilterassignee\";s:3:\"all\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (25,'darci','565491d704013245','Default','normal','yes','','n','Darci Bortolloto','darci@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (26,'debora','565491d704013245','Default','normal','yes','','n','Debora - Mãe Margarida','debora@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (27,'diana','565491d704013245','Default','normal','yes','','n','Diana','diana@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (28,'diegovenicio','565491d704013245','Default','normal','yes','','n','Diego Venicio','diegovenicio@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (29,'diogo','565491d704013245','Default','normal','yes','','n','Diogo Toigo','diogo@grupovanguarda.com','full-access-see-own-assigned-entities','','a:6:{s:16:\"pdfiltercustomer\";s:3:\"all\";s:14:\"pdfilterstatus\";s:3:\"all\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:2:\"29\";s:16:\"pdfilterassignee\";s:3:\"all\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','status','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (30,'duda','565491d704013245','Default','normal','yes','','n','Duda - Terra santa','','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (31,'ede','565491d704013245','Default','normal','yes','','n','Guidanir Perlin','ede@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (32,'eder','565491d704013245','Default','normal','yes','','n','Eder - Mãe Margarida','eder@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (33,'ednilson','5c41fe80336a065b','','','yes','','n','Ednilson','ednilson@grupovanguarda.com','full-access-see-own-assigned-entities','','a:6:{s:16:\"pdfiltercustomer\";s:1:\"1\";s:14:\"pdfilterstatus\";s:3:\"all\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:2:\"33\";s:16:\"pdfilterassignee\";s:3:\"all\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','category','No','n','n','1','1','1','1','1','1','1','','','','','','a:2:{i:0;s:7:\"default\";i:1;s:1:\"7\";}','a:10:{s:2:\"id\";b:1;s:7:\"cb_cust\";b:1;s:8:\"cb_owner\";b:1;s:11:\"cb_assignee\";b:1;s:9:\"cb_status\";b:1;s:11:\"cb_priority\";b:1;s:11:\"cb_category\";b:1;s:10:\"cb_duedate\";b:1;s:12:\"cb_alarmdate\";b:1;s:15:\"cb_creationdate\";b:1;}','');
INSERT INTO `judasloginusers` VALUES (34,'edsonroberto','565491d704013245','Default','normal','yes','','n','Edson Roberto','edsonroberto@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (35,'elisiane','565491d704013245','Default','normal','yes','','n','Elisiane - Rc','elisiane@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (36,'elizangela','565491d704013245','Default','normal','yes','','n','Elizangela','elizangela@grupovanguarda.com','full-access-see-own-assigned-entities','','a:6:{s:16:\"pdfiltercustomer\";s:1:\"2\";s:14:\"pdfilterstatus\";s:3:\"all\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:2:\"36\";s:16:\"pdfilterassignee\";s:3:\"108\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (37,'deleted_user_1149702348_emersonguarenti','565491d704013245','Default','normal','no','','n','Emerson Guarenti','emersonguarenti@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (38,'emersonguarienti','565491d704013245','Default','normal','yes','','n','Emerson Guarienti','emersonguarienti@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (39,'emilio','565491d704013245','Default','normal','yes','','n','Emilio Telles','emilio@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (40,'fazseteplacas','565491d704013245','Default','normal','yes','','n','Faz Sete Placas','fazseteplacas@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (41,'fernanda','565491d704013245','Default','normal','yes','','n','Fernanda - Terra Santa','fernanda@grupovanguarda.com','full-access-see-own-assigned-entities','','a:6:{s:16:\"pdfiltercustomer\";s:3:\"all\";s:14:\"pdfilterstatus\";s:3:\"all\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:2:\"27\";s:16:\"pdfilterassignee\";s:3:\"all\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (42,'fernando','565491d704013245','Default','normal','yes','','n','Fernando - Rc','fernando@fernanda@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (43,'filipe','565491d704013245','Default','normal','yes','','n','Filipe Fenner','filipe@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (44,'francione','565491d704013245','Default','normal','yes','','n','Francione','francione@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (45,'freo','565491d704013245','Default','normal','yes','','n','Freo','freo@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (46,'geovani','565491d704013245','Default','normal','yes','','n','Geovani Piva','geovani@grupovanguarda.com','full-access-see-own-assigned-entities','','a:6:{s:16:\"pdfiltercustomer\";s:3:\"all\";s:14:\"pdfilterstatus\";s:6:\"Aberto\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:3:\"all\";s:16:\"pdfilterassignee\";s:3:\"all\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (47,'gustavo','565491d704013245','Default','normal','yes','','n','Gustavo - Terra Santa','gustavo@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (48,'izaias','565491d704013245','Default','normal','yes','','n','Izaias Altoe','izaias@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (49,'jairo','565491d704013245','Default','normal','yes','','n','Jairo Rc','','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (50,'jeferson','565491d704013245','Default','normal','yes','','n','Jeferson - Mãe Margarida','jeferson@grupovanguarda.com','full-access-see-own-assigned-entities','','','category-----DESC','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (51,'jhenrique','565491d704013245','Default','normal','yes','','n','Jose Henrique - Zeca','jhenrique@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (52,'joaoalberto','565491d704013245','Default','normal','yes','','n','João Alberto','joaoalberto@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (53,'joaoleonardo','565491d704013245','Default','normal','yes','','n','João Leonardo Duarte','joãoleonardo@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (54,'joaquim','565491d704013245','Default','normal','yes','','n','Joaquim','joaquim@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (55,'joice','565491d704013245','Default','normal','yes','','n','Joice - Rc','','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (56,'josy','565491d704013245','Default','normal','yes','','n','Josy - Financeiro','josy@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (57,'juliana','565491d704013245','Default','normal','yes','','n','Juliana Arruda','juliana@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (58,'laureni','565491d704013245','Default','normal','yes','','n','Laureni','laureni@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (59,'lauri','565491d704013245','Default','normal','yes','','n','Lauri - Ideal Porc','lauri@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (60,'leandro','565491d704013245','','','yes','','n','Leandro Vicentin','leandro@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (61,'lucelene','565491d704013245','Default','normal','yes','','n','Lucelene','lucelene@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (62,'luciana','565491d704013245','Default','normal','yes','','n','Luciana Boeri','luciana@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (63,'madjer','565491d704013245','Default','normal','yes','','n','Madjer Tischler','madjer@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (64,'marcioideal','565491d704013245','Default','normal','yes','','n','Marcio - Ideal Porc','marcioideal@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (65,'marciojose','565491d704013245','','','yes','','n','marcio José','marciojose@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (66,'marcior','565491d704013245','Default','normal','yes','','n','Marcio - Terra Santa','marcior@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (67,'marcos','565491d704013245','Default','normal','yes','','n','Marcos Soares','marcos@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (68,'mariomartins','565491d704013245','Default','normal','yes','','n','Mario Martins','mariomartins@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (69,'marlene','565491d704013245','Default','normal','yes','','n','Marlene','marlene@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (70,'marlon','565491d704013245','Default','normal','yes','','n','Marlon Buss','marlon@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (71,'moacir','565491d704013245','Default','normal','yes','','n','Moacir - Terra Santa','moacir@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (72,'nelio','565491d704013245','Default','normal','yes','','n','Nelio - Patrimonio','nelio@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (73,'neusa','565491d704013245','Default','normal','yes','','n','Neusa Tissiani Pivetta','neusa@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (74,'neusaacvan','565491d704013245','Default','normal','yes','','n','Neusa - Acvan - Rc','neusaacvan@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (75,'oclair','565491d704013245','Default','normal','yes','','n','Oclair - Eng Florestal','oclair@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (76,'odair','565491d704013245','Default','normal','yes','','n','Odair - Compras','odair@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (77,'odinei','565491d704013245','Default','normal','yes','','n','Odinei','odinei@@grupovanguarda.com','full-access-see-own-assigned-entities','','a:6:{s:16:\"pdfiltercustomer\";s:1:\"6\";s:14:\"pdfilterstatus\";s:3:\"all\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:2:\"77\";s:16:\"pdfilterassignee\";s:3:\"108\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (78,'oficinarceu','565491d704013245','Default','normal','yes','','n','Oficina Rc','oficinarceu@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (79,'olavo','565491d704013245','Default','normal','yes','','n','Olavo Pivetta Junior','olavo@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (80,'otaviano','72fbc90c1eb5ef6d','Default','normal','yes','','n','Otaviano Pivetta','','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (81,'paola','565491d704013245','','','yes','','n','Paola','paola@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (82,'paula','565491d704013245','Default','normal','yes','','n','Paula Dalmolin','paula@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (83,'paularegina','22a5d0652c5a1dda','','','yes','','n','Paula Regina','paularegina@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (84,'pedro','565491d704013245','Default','normal','yes','','n','Pedro Tissiani','pedro@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (85,'rafael','565491d704013245','Default','normal','yes','','n','Rafael Pivetta','rafael@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (86,'rafaelgalan','565491d704013245','Default','normal','yes','','n','Rafael Galan','rafaelgalan@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (87,'rafaelmarcos','565491d704013245','Default','normal','yes','','n','Rafael Marcos','rafaelmarcos@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (88,'reginaldopuccini','565491d704013245','Default','normal','yes','','n','Reginaldo Puccini','reginaldopuccini@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (89,'reginaldovanz','565491d704013245','Default','normal','yes','','n','Reginaldo vanz','reginaldovanz@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (90,'rene','565491d704013245','Default','normal','yes','','n','Rene Domeraski','rene@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (91,'robertocamilo','565491d704013245','Default','normal','yes','','n','Roberto Camilo','robertocamilo@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (92,'rodinei','565491d704013245','Default','normal','yes','','n','Rodinei Frangiotti','rodinei@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (93,'rodrigo','565491d704013245','Default','normal','yes','','n','Rodrigo - Tec Seguran','rodrigo@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (94,'sandro','565491d704013245','Default','normal','yes','','n','Sandro Dotto','sandro@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (95,'seco','565491d704013245','Default','normal','yes','','n','Seco - Mãe Margarida','seco@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (96,'sitio1','565491d704013245','Default','normal','yes','','n','Sitio1','sitio1@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (97,'syllas','565491d704013245','Default','normal','yes','','n','Syllas Lima','syllas@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (98,'telefonista','565491d704013245','Default','normal','yes','','n','Telefonista - Fernanda','telefonista@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (99,'thiagobilibio','565491d704013245','Default','normal','yes','','n','Thiago Bilibio','thiagobilibio@grupovanguarda.com','full-access-see-own-assigned-entities','','','eid','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (100,'thiagoperoza','565491d704013245','Default','normal','yes','','n','thiago Peroza','thiagoperoza@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (101,'thiagopandolfi','565491d704013245','Default','normal','yes','','n','Thiago Pandolfi','thiagopandolfi@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (102,'transportes','565491d704013245','Default','normal','yes','','n','Transportes - Gilson','transportes@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (103,'valdir','565491d704013245','Default','normal','yes','','n','Valdir - Mãe Margarida','valdir@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (104,'vanderlei','565491d704013245','Default','normal','yes','','n','Vanderlei','vanderlei@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (105,'wallace','565491d704013245','Default','normal','yes','','n','Wallace','wallace@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (106,'welington','565491d704013245','Default','normal','yes','','n','Welington - Engenheiro Agronomo','welington@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (107,'wilson','565491d704013245','Default','normal','yes','','n','Wilson Fuentes','wilson@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (108,'Maninho','22bb56960e1a7520','','','yes','','n','Maninho Vanguarda','maninho@grupovanguarda.com','rw','yes','a:6:{s:16:\"pdfiltercustomer\";s:3:\"all\";s:14:\"pdfilterstatus\";s:6:\"Aberto\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:3:\"all\";s:16:\"pdfilterassignee\";s:3:\"all\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','Yes','n','n','','','','','','','','','','','','','a:2:{i:0;s:7:\"default\";i:1;s:1:\"7\";}','','');
INSERT INTO `judasloginusers` VALUES (109,'marcioandre','7d88385c16769ee0','','','yes','','n','marcioandre','','full-access-see-own-assigned-entities','','a:6:{s:16:\"pdfiltercustomer\";s:1:\"1\";s:14:\"pdfilterstatus\";s:3:\"all\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:3:\"109\";s:16:\"pdfilterassignee\";s:3:\"108\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (110,'Sandra','565491d704013245','','','yes','','n','Sandra','sandra@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (111,'Roberta','565491d704013245','Default','normal','yes','','n','Roberta - Estoques','roberta@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (112,'Angelica - Compras','565491d704013245','Default','normal','yes','','n','Angelica Capelari','angelica@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (113,'Divino - Ideal Porc','0b53348b76b68285','Default','normal','yes','','n','Divino Pereira de Resende','divino@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (114,'Sednei','180e0a7b552b7c49','','','yes','','n','Sednei - TI Grupo Vanguarda','sednei@grupovanguarda.com','rw','yes','','','Yes','n','n','','','','','','','','','','','','','a:2:{i:0;s:7:\"default\";i:1;s:1:\"7\";}','','');
INSERT INTO `judasloginusers` VALUES (115,'wallison','565491d704013245','','','yes','','n','Wallison','wallison@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (116,'fabio','565491d704013245','Default','normal','yes','','n','Fabio Avila','fabio@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (117,'Michel','565491d704013245','Default','normal','yes','','n','Michel Melina','melina@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (118,'Elton','565491d704013245','Default','normal','yes','','n','Elton Rufino da Silva','elton@grupovanguarda.com','full-access-see-own-assigned-entities','','a:6:{s:16:\"pdfiltercustomer\";s:3:\"all\";s:14:\"pdfilterstatus\";s:3:\"all\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:3:\"all\";s:16:\"pdfilterassignee\";s:3:\"114\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (119,'Paulo (Laboratorio)','565491d704013245','Default','normal','yes','','n','Paulo José Santana dos Santos','','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (120,'Paulo Jose','565491d704013245','','','yes','','n','Paulo José Santana dos Santos','','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (121,'Tiara','565491d704013245','Default','normal','yes','','n','Tiara','tiarar@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (122,'Geraldo','565491d704013245','Default','normal','yes','','n','Geraldo Pereira Junior - SESMET','geraldo@grupovanguarda.com','full-access-see-own-assigned-entities','','','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (123,'saulo','244409ed1e6ec78e','','','yes','','n','Saulo','','full-access-see-own-assigned-entities','','','','No','n','n','1','1','1','1','1','1','1','','','','','','a:1:{i:0;s:7:\"default\";}','','');
INSERT INTO `judasloginusers` VALUES (124,'Arlei','27ce1dc07624b17a','Default','normal','yes','','n','Arlei Manfroi','','rw','yes','a:6:{s:16:\"pdfiltercustomer\";s:3:\"all\";s:14:\"pdfilterstatus\";s:3:\"all\";s:16:\"pdfilterpriority\";s:3:\"all\";s:13:\"pdfilterowner\";s:3:\"all\";s:16:\"pdfilterassignee\";s:3:\"all\";s:18:\"pdfilterextrafield\";s:6:\"a:0:{}\";}','','No','n','n','','','','','','','','','','','','','a:1:{i:0;s:7:\"default\";}','','');
